### ISSUE TITLE
Enable logging of netty events

### ISSUE THREAD

**Issue by david-katz** [hivemq/hivemq-mqtt-client#123]
events in the pipeline can be logged in pretty print with a handler:

`InternalLoggerFactory.setDefaultFactory(Slf4JLoggerFactory.INSTANCE);
pipeline.addLast("logger", new LoggingHandler(LogLevel.DEBUG));
`

Note: this issue should be done together with one that enables logging generally, for instance by using SLF4J.

**Comment by SgtSilvio** [comment]
Closed as it is not clear which value it provides.
