### ISSUE TITLE
TLS session resumption and hostname verification

### ISSUE THREAD

**Issue by SgtSilvio** [hivemq/hivemq-mqtt-client#201]
- Caching SslContext to enable TLS session resumption
- Hostname verification

**Comment by norrland1** [comment]
We are also interested in a client solution for TLS session resumption. 
Using session id's leads to a dramatic reduction in data consumption which is important for IOT devices on cellular networks.

**Comment by SgtSilvio** [comment]
@norrland1 please check out version 1.2.0 which enables TLS session resumption.
