### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by SgtSilvio** [hivemq/hivemq-mqtt-client#213]
The following has to added to the app build.gradle file
```
android {
    ...
    packagingOptions {
        exclude 'META-INF/INDEX.LIST'
        exclude 'META-INF/io.netty.versions.properties'
    }
}
```
And of course this permission has to be added to the AndroidManifest.xml
`<uses-permission android:name="android.permission.INTERNET"/>`

**Comment by SgtSilvio** [comment]
Android should be added to the documentation

**Comment by SgtSilvio** [comment]
Netty and JCTools can not be proguarded well, so add these proguard rules:
```
-keepclassmembernames class io.netty.** {
    *;
}

-keepclassmembernames class org.jctools.** {
    *;
}
```

**Comment by SgtSilvio** [comment]
Works on API 24+ (Android 7.0+)

Lambdas, method references, static and default methods can be compiled to lower versions by specifying:
```
android {
    ...
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
    ...
}
```
Unfortunately `java.util.function.*`, `java.util.Optional`, `java.util.concurrent.CompletableFuture` are only available on API 24+
Reference: https://developer.android.com/studio/write/java8-support

**Comment by SgtSilvio** [comment]
Proguard 6.1 supports backporting streams (including `java.util.function.*`, `java.util.Optional`)
Unfortunately `java.util.concurrent.CompletableFuture` can not be backported yet.
https://www.guardsquare.com/en/blog/proguard-61-released

**Comment by android-bash** [comment]
So there is no way i can use following/similar on API level < 23 ?

    mClient.toAsync().subscribeWith()
                                .topicFilter(topic)
                                .qos(MqttQos.EXACTLY_ONCE)
                                .callback(new Consumer<Mqtt3Publish>() {
                                    @Override
                                    public void accept(Mqtt3Publish mqtt3Publish) {
                                        Log.e(HiveMqttService.class.getSimpleName(),
                                                mqtt3Publish.getTopic().toString());
                                    }
                                })
                                .send()
                                .whenComplete((subAck, throwable) -> {
                                    if (throwable == null) {
                                        Log.e(HiveMqttService.class.getSimpleName(), "Subscribed " + topic);
                                    } else {
                                        Log.e(HiveMqttService.class.getSimpleName(), "Error on " + topic + " " + throwable.getMessage());
                                    }
                                 });

**Comment by SgtSilvio** [comment]
The gradle plugin [Android RetroFix](https://github.com/SgtSilvio/android-retrofix) can backport `java.util.function.*`, `java.util.Optional`, `java.util.concurrent.CompletableFuture` and more.

**Comment by android-bash** [comment]
Wow cool. Thanks a lot. This MQTT Client Library is the best.

**Comment by SgtSilvio** [comment]
Android Support is now documented here: https://hivemq.github.io/hivemq-mqtt-client/docs/installation/android.html
