### ISSUE TITLE
Make HiveMQ Client OSGi compliant

### ISSUE THREAD

**Issue by alexweirig** [hivemq/hivemq-mqtt-client#269]
Hello,

could you please make the client library OSGi compliant be generating a full MANIFEST.MF file with the correct IMPORT and EXPORT packages statements.

This would allow users to deploy the client into an OSGi container (Felix, Equinox, Karaf ...) without any further actions required.

maven has the required plugins to generate valid OSGi bundles. The best and most reliable solution would probably be to use the bnd(tools) plugin for maven.

https://enroute.osgi.org/about/115-bnd-plugins.html

Many thanks in advance

**Comment by siepkes** [comment]
If you have experience with OSGi it might be best to create a PR for it. I don't know if the maintainers of this project have OSGi experience but OSGi can be a bit intimidating if you have never worked with it before.

**Comment by dobermai** [comment]
OSGi is not something we‘re using ourselves and we are not aware of current library users with OSGi. We‘re open for contributions, though.

**Comment by J-N-K** [comment]
I'm currentyl checking if we can use the HiveMQ client in openHAB and we would greatly benefit from an OSGi package. 
One question (not very experienced with netty): Do we need excactly `4.1.32.Final` or can we use everthing from 4.1 to 4.2?
