### ISSUE TITLE
default way cannot set websocketconfig

### ISSUE THREAD

**Issue by BEWINDOWEB** [hivemq/hivemq-mqtt-client#271]
## Behavior
i want to use websocket (no ssl):
```
Mqtt3ClientBuilder clientBuilder = MqttClient.builder()
                                               .identifier(clientId)
                                               .serverHost(host)
                                               .serverPort(port)
                                               .useMqttVersion3();
clientBuilder.useWebSocket().serverPath(websocketUrl).subprotocol(subProtocol);
return clientBuilder.build();
```
cannot link, i debug it and find that the clientBuilder attr websocketconfig is null:
![image](https://user-images.githubusercontent.com/6178098/56343181-9e72a380-61ec-11e9-9a13-c6ef57b1033d.png)
so i changed another way to do websocket link:
```
MqttWebSocketConfig mqttWebSocketConfig =
     MqttWebSocketConfig.builder().serverPath(websocketUrl).subprotocol(subProtocol).build();
 clientBuilder.useWebSocket(mqttWebSocketConfig);
return clientBuilder.build();
```
this way is ok:
![image](https://user-images.githubusercontent.com/6178098/56343284-e2fe3f00-61ec-11e9-8fd0-3c6cf8886e93.png)

## Details
- Affected HiveMQ MQTT Client version(s): 1.0.0
- Used JVM version: 1.8

**Comment by SgtSilvio** [comment]
Nice to see your interest in the HiveMQ MQTT Client.

You have to apply the WebSocket configuration by using the method `applyWebSocketConfig`.

```java
Mqtt3Client client = Mqtt3Client.builder()
        .identifier(clientId)
        .serverHost(host)
        .serverPort(port)
        .useMqttVersion3()
        .useWebSocket()
            .serverPath(websocketUrl).subprotocol(subProtocol).applyWebSocketConfig()
        .build();
```

I will close this issue as resolved. If you have another question please feel free to open a new issue.
