### ISSUE TITLE
Blocking subscribe with timeout

### ISSUE THREAD

**Issue by dowhiletrue** [hivemq/hivemq-mqtt-client#292]
I would like to implement an async Apache Camel request/reply pattern using the Mqtt5RxClient.

Therefore I need to block the thread that subscribes the topic until the suback is sent back. I then want to wait for the response with a given timeout asynchronously.

My code looks as follows:
```
subscribeScenario
   .timeout(...) // timing out request/reply if Mqtt5Publish does not arrive
   .take(1) // request/reply has only one Mqtt5Publish
   .subscribe(onNext, onError); // handle Camel's async callback

subscribeScenario.subscribeSingleFuture().get() // block calling thread until sub is ack.

publish(myMqtt5PublishWithResponseTopic);
```

Using this code, processing blocks (deadlocks?) after one request/reply since there are only 4 threads available.

If I change the Schedulers to IO then it works and uses a new thread for each request/response which doesn't scale well.

If I don't `subscribeSingleFuture` everything works as well but creates race conditions with the replier.

Any help would be appreciated!

**Comment by SgtSilvio** [comment]
If I understand correctly you want to
1. subscribe to the response topic
1. publish to the request topic after the SubAck has been received

You do not need to block the thread until the SubAck is received.
You could do something like this:
```java
client.toRx().subscribeStreamWith()
        .topicFilter("responseTopic")
        .applySubscribe()
        .doOnSingle(subAck -> client.toAsync().publishWith().topic("requestTopic").send())
        .firstOrError()
        .timeout(10, TimeUnit.SECONDS)
        .subscribe(publish -> {
            // handle response message
        }, throwable -> {
            // handle error
        });
```

**Comment by dowhiletrue** [comment]
I need to block the calling thread until the subAck is done, since once this thread is released it sends a pubRec back to another topic:

![Sequence Diagram](https://www.plantuml.com/plantuml/img/TP51RWCX34NtdCBAAbta0br4a-O2KNe2SCmK1HXYGwMvVPbCCc4gXHNYF_zlcqwovbo2LqgbUdFeaeuPDbyyN8ate0LuhHnr80y76IF2oINoBjATwzywc7yMPqf-XEzHCeKxO6iymsuFFNm23b5Ae6qUaiCFfJ6xNvsf-gj-OWnNI8eHP6SgHY4zKBDuL5dZjTLUfQaOx-HdotGh9BdL7_APK5se2PwDRTFSkdX1hR9FCl6097LzT9iVL-5DPqsIRKPOrl0YvzDHl4m_zWS0)

**Comment by SgtSilvio** [comment]
> I need to block the calling thread until the subAck is done, since once this thread is released it sends a pubRec back to another topic

Which library are you using for that?
Imho you should return a future from the async pipeline that completes when the suback is received and then add a listener that send back the PubRec.

**Comment by SgtSilvio** [comment]
> And by the way... is the timeout valid for the subAck and the first publish?

The timeout only applies to the Publish. So if you specify a timeout of 10 seconds the SubAck AND the Publish must be received in 10 seconds (not 10s timeout for SubAck + 10s timeout for Publish).

**Comment by dowhiletrue** [comment]
> > I need to block the calling thread until the subAck is done, since once this thread is released it sends a pubRec back to another topic
> 
> Which library are you using for that?
> Imho you should return a future from the async pipeline that completes when the suback is received and then add a listener that send back the PubRec.

**Comment by SgtSilvio** [comment]
@dowhiletrue Can i ask why you closed the issue? Did you solve it?

**Comment by dowhiletrue** [comment]
> > I need to block the calling thread until the subAck is done, since once this thread is released it sends a pubRec back to another topic
> 
> Which library are you using for that?
> Imho you should return a future from the async pipeline that completes when the suback is received and then add a listener that send back the PubRec.

unintentionally closed, sorry!

I use HiveMq async client to `consume(topic)` and [process](http://camel.apache.org/asynchronous-processing.html) it asynchronously. So the HiveMq async consume(topic)` thread should wait until the subscribtion on the temp topic is made and the message is published on the other topic

**Comment by dowhiletrue** [comment]
[Added a gist to illustrate the problem](https://gist.github.com/dowhiletrue/3bc1137dda8fdc54378082aa56266c6a)

The `waitForSubAck` breaks the test. I don't know how to implement it differently without losing the ability to wait for the PUBREC to be sent to start topic after the message is published on the tempTopic.

**Comment by SgtSilvio** [comment]
There is a misconception regarding the acknowledgement of incoming messages:
The PubAck/PubRec is not delayed until the callback returns, so it does not make sense to block there.
Why do you require that the client first receives the SubAck before sending the PubAck/PubRec? This feels like a misuse of MQTT. PubAck/PubRec are used to ensure QoS guarantees and should not be used for other application level purposes. (correct me if you have a specific use case for it)

**Comment by dowhiletrue** [comment]
Ah ok, thanks for pointing that out! :-)

I would like to ensure that a message, read from topic 1 is published to topic 2 at least once. If the PubRec is sent to topic 1 before the message is published to topic 2, the message might get lost upon failure of the processing system.

**Comment by SgtSilvio** [comment]
For this you would need the feature of manual acknowledgements.
This is already known. I create a feature issue #304 . Please vote on it.

**Comment by dowhiletrue** [comment]
Thanks a lot for your valuable support Silvo!
