### ISSUE TITLE
Error is logged if subscribed with 2+ subscriptions and session expires

### ISSUE THREAD

**Issue by SgtSilvio** [hivemq/hivemq-mqtt-client#295]
identified with #293 

## Expected behavior
No error is logged if subscribed with 2+ subscriptions and when the session expires

## Actual behavior
RxJavaPlugins.onError is called when session expires.

### Steps
1. Subscribe with stream with 2+ subscriptions
1. Expire session
1. RxJavaPlugins.onError is called by mistake

### Reproducer code
See #293 

## Details
- Affected HiveMQ MQTT Client version(s): 1.1.0, 1.0.1, 1.0.0
- Used JVM version: any

**Comment by tchupp** [comment]
Digging into a debug session, it seems that somehow the same reference to a `flow` is being added multiple times as a `TopicTreeEntry` in a `MqttSubscriptionFlowTree `

The first time through the loop `onError` is called properly, subsequent times end up calling `RxJavaPlugins.onError` internally.

https://github.com/hivemq/hivemq-mqtt-client/blob/1dce392b514636e07883efe3ee915876644173cc/src/main/java/com/hivemq/client/internal/mqtt/handler/publish/incoming/MqttSubscriptionFlowTree.java#L333

**Comment by SgtSilvio** [comment]
> Digging into a debug session, it seems that somehow the same reference to a `flow` is being added multiple times as a `TopicTreeEntry` in a `MqttSubscriptionFlowTree `
> 
> The first time through the loop `onError` is called properly, subsequent times end up calling `RxJavaPlugins.onError` internally.
> 
> https://github.com/hivemq/hivemq-mqtt-client/blob/1dce392b514636e07883efe3ee915876644173cc/src/main/java/com/hivemq/client/internal/mqtt/handler/publish/incoming/MqttSubscriptionFlowTree.java#L333

Thanks for trying to debug. 👍 
The `MqttSubscriptionFlowTree` stores a reference to the flow for every subscription, so multiple calls to onError with the same exception are expected and the log is therefore wrong in this case. PR is created.
