### ISSUE TITLE
Manual acknowledgement

### ISSUE THREAD

**Issue by SgtSilvio** [hivemq/hivemq-mqtt-client#304]

**Comment by dowhiletrue** [comment]
According to https://github.com/hivemq/hivemq-mqtt-client/issues/292#issuecomment-502992449 and https://github.com/hivemq/hivemq-mqtt-client/issues/292#issuecomment-503304574 it is not possible to receive AND process a message at least once. Message may get lost, if the app terminates ungracefully right after a message is acknowledged, but not yet processed.

Therefore this feature or another mechanism, that ACKs a message after the callback is called would make sense for applications, that relay on guaranteed message processing.

So please, dear GitHub user vote for this feature!

**Comment by SgtSilvio** [comment]
@dowhiletrue manual message acknowledgement is finally part of version 1.2.0, please check it out

**Comment by yilezhu** [comment]
Is there any case of manual message acknowledgement  by mqtt5client?
