### ISSUE TITLE
Cancel automatic reconnect calling connect or disconnect

### ISSUE THREAD

**Issue by SgtSilvio** [hivemq/hivemq-mqtt-client#306]

**Comment by degill** [comment]
Hey there. 
Is there any chance to cancel automatic reconnect? Calling `disconnect()` won't help since it will throw because we are not connected.

**Comment by SgtSilvio** [comment]
Hi @degill 
Yes, you can add a DisconnectedListener and set reconnect to false, for example:
```java
final AtomicBoolean cancelReconnect = new AtomicBoolean(false);
Mqtt5Client.builder()
        .automaticReconnectWithDefaultConfig()
        .addDisconnectedListener(context -> {
            if (cancelReconnect.get()) {
                context.getReconnector().reconnect(false);
            }
        })
        ...
```

**Comment by PMacho** [comment]
> Hi @degill
> Yes, you can add a DisconnectedListener and set reconnect to false, for example:
> 
> ```java
> final AtomicBoolean cancelReconnect = new AtomicBoolean(false);
> Mqtt5Client.builder()
>         .automaticReconnectWithDefaultConfig()
>         .addDisconnectedListener(context -> {
>             if (cancelReconnect.get()) {
>                 context.getReconnector().reconnect(false);
>             }
>         })
>         ...
> ```

Assuming, there is already an ongoing delayed reconnection started, I guess, this approach will fail?

**Comment by flopfl** [comment]
Hei @PMacho 
Did you find a solution to cancel the ongoing delayed reconnect?
You won't be able to manually call connect either since the client thinks it's in the process of reconnecting.

**Comment by PMacho** [comment]
> Hei @PMacho 
> 
> Did you find a solution to cancel the ongoing delayed reconnect?
> 
> You won't be able to manually call connect either since the client thinks it's in the process of reconnecting.

Kind of. We wrote a wrapper around this client that imitates the reconnect by rebuilding and reconnecting all pipelines. 
It still suffers from the fact that occasionally the server refuses to reconnect. 
However, I can't share the source here. Sorry for that. 

Just a hint if you are planning the same. When reconnecting you'll get messages from the server before actually subscribing.

**Comment by flopfl** [comment]
Okay, thanks for the hint :).

**Comment by pglombardo** [comment]
Hi all - since this issue hasn't had any updates recently I will close it out.  Thanks everyone for the input.  If anything remains, feel free to file another issue.  We'd be happy to help out.
