### ISSUE TITLE
Allow specifying a local bind-address

### ISSUE THREAD

**Issue by sbaier1** [hivemq/hivemq-mqtt-client#308]
## Problem or use case

When multiple interfaces are present, the client will currently use the first interface providing a route to the target broker. It would be handy to be able to specify a local bind-address or interface to use for the connection, so we have more control over how the connection is established.

## Preferred solution or suggestions

Provide a configuration option in the builder and set the interface or local bind address accordingly.

**Comment by android-bash** [comment]
Any help with https://github.com/hivemq/hivemq-mqtt-client/issues/310 ?
