### ISSUE TITLE
How can i connect for the following setting?

### ISSUE THREAD

**Issue by android-bash** [hivemq/hivemq-mqtt-client#310]
## Expected behavior
Need a way to connect to this broker. I am able to connect using MqttBox.

Host : dev.trailers.com:8094/mqtt
Protocol : wss

## Actual behavior
Unable to connect to client due to Connection failed exception. It says Unable to resolve host.
But I am able to connect using MqttBox.
<img width="630" alt="Screenshot 2019-07-04 at 4 49 11 PM" src="https://user-images.githubusercontent.com/21264096/60663168-152e4d00-9e7c-11e9-8907-f5fed8b7cd9f.png">

**Comment by SgtSilvio** [comment]
`dev.trailers.com:8094/mqtt` is not the host
host: `dev.trailers.com`
port: `8094`
websocket-path: `mqtt`

So the code should look like:
```java
Mqtt3Client.builder()
        .serverHost("dev.trailers.com")
        .serverPort(8094)
        .webSocketConfig().serverPath("mqtt").applyWebSocketConfig()
        .sslWithDefaultConfig()
        ...
```

If this does not solve your problem, just let me know and I will reopen this issue.

**Comment by SgtSilvio** [comment]
I removed your comments in the two linked issues, as they do not relate to this issue.

**Comment by android-bash** [comment]
Sure no problem. I was just stuck. So was trying out for help. Thanks for your reply. I will try this and get back to you.

**Comment by android-bash** [comment]
After connecting as above mentioned, how can i listen for successful subscription or failure in subscription? Am i doing something wrong in callback? I need to know whether subscription was successful or not.

    mClient.toAsync().subscribeWith()
                                .topicFilter(entry.getKey())
                                .qos(MqttQos.EXACTLY_ONCE)
                                .callback(new Consumer<Mqtt3Publish>() {
                                    @Override
                                    public void accept(Mqtt3Publish mqtt3Publish) {
                                        Log.e("Subscribed to", mqtt3Publish.getTopic().toString());
                                       //This is not being called
                                    }
                                })
                                .send();

**Comment by SgtSilvio** [comment]
The callback is for the publish messages you receive for the subscription.
Every call of the Async API returns a `CompletableFuture`, e.g. `subscribe` returns `CompletableFuture<SubAck>`
```java
client.toAsync().subscribeWith()
        .topicFilter("test")
        .callback(publish -> System.out.println("Received message for subscription"))
        .send()
        .whenComplete((subAck, throwable) -> {
            if (throwable == null) {
                System.out.println("Subscribed successfully");
            } else {
                throwable.printStackTrace();
            }
        });
```

**Comment by android-bash** [comment]
Got it. Thanks a lot. Also how can i support this in API level <= 23 ?

**Comment by SgtSilvio** [comment]
As this is a different topic, please continue the discussion in #213

**Comment by android-bash** [comment]
Sure. Thank you so much.

**Comment by android-bash** [comment]
client.toAsync().subscribeWith()
        .topicFilter("test")
        .callback(publish -> System.out.println("Received message for subscription"))
        .send()
        .whenComplete((subAck, throwable) -> {
            if (throwable == null) {
                System.out.println("Subscribed successfully");
            } else {
                throwable.printStackTrace();
            }
        });

How can i know which topic got subscribed to?
