### ISSUE TITLE
Rx thread persistance

### ISSUE THREAD

**Issue by timtay-microsoft** [hivemq/hivemq-mqtt-client#314]
More of a question than a bug, because it feels like I'm missing something. When I create an async client, there are some threads that are spun up including "RxCachedWorkerPoolEvictor-1", and "RxSchedulerPurge-1". When I want to close down all mqtt communication in my application, I don't see a way to stop these threads. Even after disconnecting the mqtt client, these threads are still alive.

I see similar threads spawned when I send connect and disconnect packets where the threads are named "RxComputationThreadPool-#" that I'd also like to close

Is there an API to accomplish this? Or is it by design?

### Steps
Run the reproducer code, but note which threads are alive before and after the mqtt client is created

### Reproducer code

```java
mqttClient = MqttClient.builder()
                .useMqttVersion3()
                .serverHost(serverURI)
                .serverPort(8883)
                .sslWithDefaultConfig()
                .identifier(clientId)
                .build()
                .toAsync();

mqttClient.connectWith()
                .simpleAuth()
                .username(username)
                .password(password.getBytes())
                .applySimpleAuth()
                .send()
                .whenComplete((mqtt3ConnAck, throwable) -> {})
                .get();
```

## Details
- Affected HiveMQ MQTT Client version(s): 1.1.1
- Used JVM version: 1.8.0_201

**Comment by SgtSilvio** [comment]
Hi @timtay-microsoft 

The threads you mentioned are created by RxJava.
The "RxComputationThreadPool-#" threads are used for the asynchronous handling of messages, so they are needed for the Rx and the Async API. The Blocking API does not use them.

If you are sure that there are no pending tasks anymore, you can call `Schedulers.shutdown()` to stop all RxJava threads.
Keep in mind that you have to start them again if you want to connect a MQTT client again: `Schedulers.start()`

**Comment by timtay-microsoft** [comment]
Perfect, thanks for the clarification!
