### ISSUE TITLE
Error Code: NOT_AUTHORIZED

### ISSUE THREAD

**Issue by lukkna** [hivemq/hivemq-mqtt-client#315]
Hello,
On all production devices I keep getting this exception:
`com.hivemq.client.mqtt.mqtt3.exceptions.Mqtt3ConnAckException CONNECT failed as CONNACK contained an Error Code: NOT_AUTHORIZED`
I failed to find root cause of it, maybe someone knows what could be wrong?

I'm using client on my android app, client version: 1.1.1, rx flavor, mqtt version 3.

**Comment by clive-jevons** [comment]
Hi lukkna,

Could you provide a bit more context, please? The error message is to be expected if your broker requires some kind of client authentication (username / password or client cert). Which of those are configured on your broker?
Maybe you could post the code which is trying to create the connection?

Cheers,
C

**Comment by lukkna** [comment]
I'm using plain username-password authentication. Eventually user connects, but I get these exceptions all the time and would like to fix the issue.
Client building:
`MqttClient.builder()
                .useMqttVersion3()
                .identifier("ePCR mobile-" + currentTimeMillis())
                .serverHost(config.getHost())
                .serverPort(config.getPort())
                .automaticReconnectWithDefaultConfig()
                .addConnectedListener(this)
                .addDisconnectedListener(this)
                .buildRx()`

**Comment by clive-jevons** [comment]
You need to provide the username and password when connecting the client. E.g. something like this:

```
        Mqtt3ConnAck mqtt3ConnAck = client.connectWith()
                .simpleAuth()
                .username("myuser")
                .password("mypassword".getBytes(StandardCharsets.UTF_8))
                .applySimpleAuth()
                .applyConnect()
                .blockingGet();

```

**Comment by lukkna** [comment]
Sorry, I misunderstood and provided code of building client, but not connecting. This is the code of connecting:
`private void connect() {
        String url = config.getHost() + ":" + config.getPort();
        subscriptions.add(client.connectWith()
                .simpleAuth()
                .username(config.getUsername())
                .password(config.getPassword().getBytes())
                .applySimpleAuth()
                .applyConnect()
                .retry()
                .subscribe(connAck -> logAccordingToConnAckCode(url, connAck.getReturnCode()),
                        e -> Timber.e(e, "MQTT connection unsuccessful. Server url = [%s]", url)));
    }`

**Comment by clive-jevons** [comment]
Hi lukkna,

I used the code you posted above and ran it against a local mosquitto with auth enabled, and the client connected correctly first time with no fuss.

For further analysis we'd need a minimal example project from you which recreates the problem.

Cheers,
C

**Comment by lukkna** [comment]
I can't recreate issue myself. My app linked with crashlytics and I keep getting these there even though I know for sure that it works correctly.

**Comment by SgtSilvio** [comment]
Hi @lukkna 
You are using automatic reconnect.
If you set the username and password on the connect call, they will not be stored and reused when the client reconnects (for security reasons).
What you have to do, is setting the username and password directly on the client, so the client uses the same username/password during every (re)connect:
```java
Mqtt3Client.builder()
        .identifier("ePCR mobile-" + currentTimeMillis())
        .serverHost(config.getHost())
        .serverPort(config.getPort())
        .automaticReconnectWithDefaultConfig()
        .simpleAuth()
            .username(config.getUsername())
            .password(config.getPassword())
            .applySimpleAuth()
        .buildRx();
```

**Comment by lukkna** [comment]
Thank you for solution. I'll try it out tomorrow.
