### ISSUE TITLE
Client Thread safety

### ISSUE THREAD

**Issue by iEAmi** [hivemq/hivemq-mqtt-client#317]
Could I use client instance from different thread?
I want to share a client instance to multi thread, Is this good idea?

**Comment by SgtSilvio** [comment]
Hi @iEAmi 
All MQTT operations are safe to be called by different threads (https://hivemq.github.io/hivemq-mqtt-client/docs/mqtt_operations.html).
You can even use different API styles simultaneously.

**Comment by iEAmi** [comment]
@SgtSilvio , Thank you for fast answer.
