### ISSUE TITLE
Using MqttClientConnectedListener to resubscribe

### ISSUE THREAD

**Issue by matthjes** [hivemq/hivemq-mqtt-client#325]
Hi,

Is it possible to use a registered `MqttClientConnectedListener` to resubscribe to a topic after a reconnect? Currently the reconnect works after a crash of the broker, but not the resubscribe, so I thought to do it manually inside the listener.

This is somehow linked to issue #297.

**Comment by SgtSilvio** [comment]
Hi @matthjes 
Yes, you can use a `MqttClientConnectedListener` to resubscribe.
You have to use the Async or Rx API as it will not work with the blocking API (you are not allowed not block in the `MqttClientConnectedListener` anyway).

**Comment by matthjes** [comment]
Yes, but how can I do this? How can I access the client to call subscribe inside the listener callback? I could not find a reference to the client instance...

**Comment by clive-jevons** [comment]
One way to do it is create a listener class which can be given the client reference after it's been created - then you can set an instance of the listener on the builder before the client is created, then after you create the client, set that on the listener instance. E.g. something like in here:

https://github.com/bmwcarit/joynr/blob/1.8.3/java/messaging/mqtt/hivemq-mqtt-client/src/main/java/io/joynr/messaging/mqtt/hivemq/client/HivemqMqttClientFactory.java

**Comment by matthjes** [comment]
> One way to do it is create a listener class which can be given the client reference after it's been created - then you can set an instance of the listener on the builder before the client is created, then after you create the client, set that on the listener instance. E.g. something like in here:
> 
> https://github.com/bmwcarit/joynr/blob/1.8.3/java/messaging/mqtt/hivemq-mqtt-client/src/main/java/io/joynr/messaging/mqtt/hivemq/client/HivemqMqttClientFactory.java

D'oh, I didn't think about this solution, I was fixated on using the parameter of the listener callback method. Thank you!!
