### ISSUE TITLE
MqttDecoderException "malformed subscription identifier" by receiving a particular Message: Cause TOO_LARGE return value in MqttVariableByteInteger#decode

### ISSUE THREAD

**Issue by mofd** [hivemq/hivemq-mqtt-client#326]
## Actual behavior
By receiving one paricural retained message the HiveMq-Client throws following exception:

> com.hivemq.client.mqtt.mqtt5.exceptions.Mqtt5DisconnectException: Exception while decoding PUBLISH: malformed subscription identifier
Caused by: com.hivemq.client.mqtt.exceptions.MqttDecodeException: Exception while decoding PUBLISH: malformed subscription identifier

The cause point is MqttVariableByteInteger#decode with return value TOO_LARGE with explenation:

> if the encoded variable byte integer has more than 4 bytes 

see 'if (shift > MAX_SHIFT)'

public static int decode(final @NotNull ByteBuf byteBuf) {
        byte encodedByte;
        int value = 0;
        byte shift = 0;

        do {
            if (shift > MAX_SHIFT) {
                return TOO_LARGE;
            }
            if (!byteBuf.isReadable()) {
                return NOT_ENOUGH_BYTES;
            }
            encodedByte = byteBuf.readByte();
            final int encodedByteValue = encodedByte & VALUE_MASK;
            value += encodedByteValue << shift;
            shift += VALUE_BITS;
        } while ((encodedByte & CONTINUATION_BIT_MASK) != 0);

        if (shift > VALUE_BITS && encodedByte == 0) {
            return NOT_MINIMUM_BYTES;
        }

        return value;
}

By using other libraries like paho or clients like mqtt.fx the the message can be received without problems. Both the client and the lib are based on mqtt3. My client only use the mqtt5-features for publishing the messages.

## To Reproduce
I can only reproduce this in our local system with this one particular message. The body contains a simle JSON content. Other messages of the same type and similar content doesen't make problems by receiving. This ist the mesage content:

> {"azbId":"dfi2_fue_2","azbFahrplanlages":[],"azbLinienspezialtexts":[],"fgiFahrtspezialtexts":[],"fgiLinienspezialtexts":[],"fgiSpezialtexts":[]}

### Reproducer code
My Code is simple and looks like this:

import com.hivemq.client.mqtt.MqttClientState;
import com.hivemq.client.mqtt.datatypes.MqttQos;
import com.hivemq.client.mqtt.mqtt5.Mqtt5AsyncClient;
import com.hivemq.client.mqtt.mqtt5.Mqtt5Client;
import com.hivemq.client.mqtt.mqtt5.Mqtt5ClientBuilder;

...

public class Mqtt5Service {

	private static final Logger LOGGER = LoggerFactory.getLogger(Mqtt5Service.class);
	
	...

	public void buildAndConnect() {
		mqttClient = getBuilder()
			.identifier(configuartion.getClientId())
			.serverHost(configuartion.getUrl())
			.serverPort(configuartion.getPort())
			.automaticReconnect().initialDelay(configuartion.getAutoReconnectInitialDelayInSeconds(), TimeUnit.SECONDS).maxDelay(configuartion.getAutoReconnectMaxDelayInSeconds(), TimeUnit.SECONDS).applyAutomaticReconnect()
			.addConnectedListener(context -> {
				if (LOGGER.isDebugEnabled()) {
					LOGGER.debug("connected");
				}
			})
			.addDisconnectedListener(context -> {
				if (DISCONNECT_BY_DEMAND.equalsIgnoreCase(context.getCause().getMessage())) {
					LOGGER.debug("disconnected by demand");
				} else {
					LOGGER.error("connection lost {}", context.getReconnector().getAttempts(), context.getCause());
				}
			})
			.buildAsync();

		mqttClient.connectWith()
			.keepAlive(configuartion.getKeepAlivePingInSeconds())
			.cleanStart(true)
			.simpleAuth()
			.username(configuartion.getUser())
			.password(configuartion.getPasswd().getBytes(StandardCharsets.UTF_8))
			.applySimpleAuth()
			.send()
			.whenComplete((mqtt5ConnAck, throwable) -> {
				if (throwable != null) {
					LOGGER.error("initial connection failed", throwable);
				} else {
					if (LOGGER.isDebugEnabled()) {
						LOGGER.debug("initial connection succeeded");
					}
				}
			});
	}
	
	...

}

## Details
- Affected HiveMQ MQTT Client version(s): 1.1.2 and 1.1.0
- Used JVM version: adoptopenjdk 11.0.2+9

**Comment by SgtSilvio** [comment]
Hi @mofd 
Which MQTT broker are you using? It really seems like the broker does encode the publish message incorrectly.
The exception can only happen if you are using a MQTT 5 client to subscribe. What do you mean by "Both the client and the lib are based on mqtt3"?

**Comment by mofd** [comment]
Hi @SgtSilvio.

We use HiveMQ-Broker in version 4.1.1, I guess. I'm still waiting for detailed answare from our provider.

I received the message successfully wit following MQTT-3 clients:

- mqtt.fx 1.7.0
- paho 1.2.0
- hivemq 1.1.2 MQTT-3

Only the hivemq 1.1.2 MQTT-5 Client produce the exception.

I will inform you about our HiveMQ-Broker version, asap.

Thanks a lot

@mofd

**Comment by mofd** [comment]
Hi @SgtSilvio.

Our provider informed my that we have HiveMq 3.4.1 and not 4.1. This was a big mistake. Sorry. I think this is the cause for my problem.

Thanks a lot

@mofd

**Comment by SgtSilvio** [comment]
@mofd With HiveMQ 3.4.1 you can not connect MQTT 5 clients (MQTT 5 was introduced only with HiveMQ 4), so I think you are not using HiveMQ 3.4.1.
If I remember correctly HiveMQ 4.0.0 had an issue with encoding subscription identifiers, which was fixed in 4.0.1.

**Comment by mofd** [comment]
Hi @SgtSilvio.
Our provider still holding we have HiveMQ 3.4.1. However we should get the newest version in the next time. I'll inform you if the problem still occur after the update.
Bye
@mofd
