### ISSUE TITLE
Allow querystring in MqttWebsocketConfig

### ISSUE THREAD

**Issue by alsanrum** [hivemq/hivemq-mqtt-client#335]
## Problem or use case
Hi,
when I try use websockets that need queryString I discovered that the request is bad formatted because the MqttWebSocketInitializer is using URI class only which the serverPath argument.

## Preferred solution or suggestions
Add queryString in MqttWebSocketConfig.
Use queryString of the new MqttWeSocketConfig in URI inside of initChannel of MqttWebSocketInitializer class.

Thanks

**Comment by SgtSilvio** [comment]
Resolved by #336
