### ISSUE TITLE
Setting credentials in MqttClientDisconnectedListener

### ISSUE THREAD

**Issue by samuelbacaner** [hivemq/hivemq-mqtt-client#344]
This isn't a bug. Just a question.

The breadcrumb I'm following is the javadoc for `MqttClientReconnector#reconnectWhen(CompletableFuture<T> future, BiConsumer<? super T, ? super Throwable> callback)` which says this is `the callback that will be called after the future completes and before the client will reconnect. It can be used to set new connect properties (e.g. credentials).`

Can you eleborate on that pattern of setting the credentials? I'm using mqtt v3. Here is the structure of what I'm trying to do:

```
class DisconnectedListener implements MqttClientDisconnectedListener {

    public void onDisconnected(@Nonnull MqttClientDisconnectedContext context) {
        TypeSwitch.when(context)
                .is(Mqtt3ClientDisconnectedContext.class, context3 -> {
                    context3.getReconnector().reconnectWhen(
                            // ConnectUtils#createMqttconnect creates a fresh Mqtt3Connect object with newly generated token in the password field
                            CompletableFuture.completedFuture(ConnectUtils.createMqttConnect(true, true, 16)),
                            (mqtt3Connect, throwable) -> {
                                // how do you set the new Mqtt3Connect object? Or, more generally, a Mqtt3SimpleAuth object
                            }
                    );
                })
                .is(Mqtt5ClientDisconnectedContext.class, context5 -> {
                    throw new AssertionError("MQTT 5 is not supported by Cloud IoT Core");
                });
    }
}
```

## Details
- Affected HiveMQ MQTT Client version(s): 1.1.2
- Used JVM version: OpenJDK 11

**Comment by samuelbacaner** [comment]
Of course, I find the answer right after asking. For posterity here is what I ended up using:
```
context3.getReconnector()
     .reconnect(true)
      .connect(ConnectUtils.createMqttConnect(true, true, 16));
```

**Comment by SgtSilvio** [comment]
Nice to see that you found the answer yourself.
Just to clarify when you need to use the `reconnect` and when `reconnectWhen`:
- If `someMethod()` is blocking (for example involves a remote requests) you must use `reconnectWhen` as blocking in the DisconnectedListener is not allowed and will have performance impacts when using multiple clients. If `someMethod()` does not provide an async API, you can use `CompletableFuture.supplyAsync(() -> someMethod())`.
- If `someMethod()` is not blocking you can just use `reconnect`.

**Comment by michaeloreillyintel** [comment]
Can you show mw what you have in 
Mqtt3Connect mqtt3connect = someMethod();
that is setting the auth parameters.

**Comment by SgtSilvio** [comment]
@michaeloreillyintel I answered you in #534
