### ISSUE TITLE
Option to specify more then one server in disconnected listener ?

### ISSUE THREAD

**Issue by jayjamba** [hivemq/hivemq-mqtt-client#346]
Hi,
Below is an example in which I am connecting to server 192.168.0.1 and if this server goes down it waits for around 15 seconds in total of 3 attempts and then connects to 192.168.0.2. My concern is what if 192.168.0.2 is also down at that time, **do we have an option to specify more than 1 server in case of failure of node in Disconnected listener ?**

**Also do we have an option to connect immidiately to 192.168.0.2 in case of failure to connect to 192.168.0.1 instead of waiting for some seconds/attempts ?**

final Mqtt5BlockingClient client = Mqtt5Client.builder().identifier(UUID.randomUUID().toString())
        .serverHost("192.168.0.1").serverPort(1883).addDisconnectedListener(context -> {
        System.out.println(context.getCause());
        context.getReconnector().reconnect(true).delay(5, TimeUnit.SECONDS);
       System.out.println(context.getReconnector().getAttempts());
       if (context.getReconnector().getAttempts() > 3) {
          context.getReconnector().transportConfig().serverHost("192.168.0.2").applyTransportConfig();
       }
}).buildBlocking();

**Comment by SgtSilvio** [comment]
Hi @jayjamba 
you could do something like the following:
```java
String[] serverHosts = {"192.168.0.1", "192.168.0.2", "192.168.0.3", "192.168.0.4"};

Mqtt5Client.builder()
        .serverHost(serverHosts[0])
        .addDisconnectedListener(new MqttClientDisconnectedListener() {
            private int reconnects = 0;

            @Override
            public void onDisconnected(MqttClientDisconnectedContext context) {
                context.getReconnector().reconnect(true).delay(5, TimeUnit.SECONDS);
                if (context.getReconnector().getAttempts() > 3) {
                    reconnects++;
                    String nextHost = serverHosts[reconnects % serverHosts.length];
                    context.getReconnector().transportConfig().serverHost(nextHost).applyTransportConfig();
                }
            }
        })
        .build();
```

**Comment by SgtSilvio** [comment]
Please let me know if this helps.

**Comment by jayjamba** [comment]
Thanks for reply, I will let you know soon.
BTW you missed my one more query -  **Also do we have an option to connect immidiately to 192.168.0.2 in case of failure to connect to 192.168.0.1 instead of waiting for some seconds/attempts ?**

**Comment by SgtSilvio** [comment]
Sorry that I closed the issue although I missed your second question.

If you want to always try to connect in a round-robin fashion and only delay if you could not connect to any server in the list, you could do it like so:
```java
String[] serverHosts = {"192.168.0.1", "192.168.0.2", "192.168.0.3", "192.168.0.4"};

Mqtt5Client.builder()
        .serverHost(serverHosts[0])
        .addDisconnectedListener(new MqttClientDisconnectedListener() {
            private int reconnects = 0;

            @Override
            public void onDisconnected(MqttClientDisconnectedContext context) {
                reconnects++;
                String nextHost = serverHosts[reconnects % serverHosts.length];
                context.getReconnector()
                        .reconnect(true)
                        .transportConfig().serverHost(nextHost).applyTransportConfig();
                if (reconnects % serverHosts.length == 0) {
                    context.getReconnector().delay(5, TimeUnit.SECONDS);
                }
            }
        })
        .build();
```

**Comment by SgtSilvio** [comment]
Generally you can implement any logic you like for reconnecting.
We plan to offer a default implementation for the high availability use case where you connect to a list of brokers in the future, but currently you can implement it yourself.

**Comment by michaeloreillyintel** [comment]
I have a scenario where I use a local MQTT server while my device is on my local LAN, but when I lose connection I switch to a Cloud broker.

How can I apply different auth per server?

if (localserver){
context.getReconnector().transportConfig().serverHost(localhost).serverPort(localport).applyTransportConfig();
}else{
context.getReconnector().transportConfig().serverHost(cloudhost).serverPort(cloudport).applyTransportConfig();
//need to change the username and password here
}

This issue https://github.com/hivemq/hivemq-mqtt-client/issues/344  looks like it might help me, but unfortunately didn't show the implementation of setting the auth parameters outside of a MqttClientBuilder.

**Comment by SgtSilvio** [comment]
@michaeloreillyintel I answered you in #534
