### ISSUE TITLE
[question] Does the client support last will and testament?

### ISSUE THREAD

**Issue by tejas-n** [hivemq/hivemq-mqtt-client#347]
Does the client support setting a last will and testament message? If not, is it in the roadmap?

**Comment by SgtSilvio** [comment]
Yes, LWT/Will is supported.

You can set it when connecting:
```java
client.connectWith()
        .willPublish()
                .topic("topic")
                .qos(AT_LEAST_ONCE)
                .payload("will".getBytes())
                .applyWillPublish()
        .send()
```
(more information: https://hivemq.github.io/hivemq-mqtt-client/docs/mqtt_operations/connect.html#will)

Alternatively you can set it when building the client, the Will is then also used when reconnecting:
```java
Mqtt5Client.builder()
        .willPublish()
                .topic("topic")
                .qos(AT_LEAST_ONCE)
                .payload("will".getBytes())
                .applyWillPublish()
        .build()
```

**Comment by tejas-n** [comment]
Cool, thanks for the reply.
