### ISSUE TITLE
How can messages in a topic be consumed multiple times

### ISSUE THREAD

**Issue by wenyanwen** [hivemq/hivemq-mqtt-client#348]
public void MQTTStart() {

        final Mqtt3Connect connect = Mqtt3Connect
                .builder()
                .simpleAuth()//start
                .username("admin")//username
                .password("password".getBytes())//password
                .applySimpleAuth()//end
                .build();

        final Mqtt3BlockingClient client = MqttClient.builder()
                .useMqttVersion3()
                .serverAddress(new InetSocketAddress("127.0.0.1", 1883))//address
                //.serverAddress(new InetSocketAddress("192.168.1.203", 1883))
                .identifier(UUID.randomUUID().toString())

                .buildBlocking();
        
        client.connect(connect);
        
        
        client.subscribeWith().topicFilter("test/topic").qos(MqttQos.EXACTLY_ONCE).send();

        try (Mqtt3BlockingClient.Mqtt3Publishes publishes = client.publishes(MqttGlobalPublishFilter.ALL)) {
 
                Mqtt3Publish publishMessage = publishes.receive();
                log.info("{}", publishMessage);
                
        } catch (Exception e) {
            log.error("err", e);
        }
    }

**Comment by SgtSilvio** [comment]
Hi @wenyanwen 
What exactly do you mean by "consuming multiple times"?

If you mean that different components of your code should consume the same messages, just share the client instance with all components and call `publishes` in each component individually.
So component A has its own instance of `Mqtt3Publishes` and component B has another instance of `Mqtt3Publishes`.

Can you clarify what your use case is?

**Comment by wenyanwen** [comment]
I have a client that sends messages all the time that can read all the messages

**Comment by SgtSilvio** [comment]
Can you explain in more detail
- Which client publishes messages?
- Which client receives messages?
- What is your use case?
- What do you mean by consuming messages multiple times?

**Comment by wenyanwen** [comment]
I want this style:
MqttPublish{topic=test/topic, payload=7byte, qos=AT_LEAST_ONCE, retain=false}
MqttPublish{topic=test/topic, payload=7byte, qos=AT_LEAST_ONCE, retain=false}
MqttPublish{topic=test/topic, payload=7byte, qos=AT_LEAST_ONCE, retain=false}
MqttPublish{topic=test/topic, payload=7byte, qos=AT_LEAST_ONCE, retain=false}
MqttPublish{topic=test/topic, payload=7byte, qos=AT_LEAST_ONCE, retain=false}
MqttPublish{topic=test/topic, payload=7byte, qos=AT_LEAST_ONCE, retain=false}
MqttPublish{topic=test/topic, payload=7byte, qos=AT_LEAST_ONCE, retain=false}

**Comment by wenyanwen** [comment]
But this is the pattern:
MqttPublish{topic=test/topic, payload=3byte, qos=AT_LEAST_ONCE, retain=false}
No publish flow registered for MqttStatefulPublish{stateless=MqttPublish{topic=test/topic, payload=3byte, qos=AT_LEAST_ONCE, retain=false}, packetIdentifier=2, dup=false, topicAlias=0, subscriptionIdentifiers=[]}.
No publish flow registered for MqttStatefulPublish{stateless=MqttPublish{topic=test/topic, payload=3byte, qos=AT_LEAST_ONCE, retain=false}, packetIdentifier=3, dup=false, topicAlias=0, subscriptionIdentifiers=[]}.
No publish flow registered for MqttStatefulPublish{stateless=MqttPublish{topic=test/topic, payload=3byte, qos=AT_LEAST_ONCE, retain=false}, packetIdentifier=4, dup=false, topicAlias=0, subscriptionIdentifiers=[]}.
No publish flow registered for MqttStatefulPublish{stateless=MqttPublish{topic=test/topic, payload=3byte, qos=AT_LEAST_ONCE, retain=false}, packetIdentifier=5, dup=false, topicAlias=0, subscriptionIdentifiers=[]}.
No publish flow registered for MqttStatefulPublish{stateless=MqttPublish{topic=test/topic, payload=3byte, qos=AT_LEAST_ONCE, retain=false}, packetIdentifier=6, dup=false, topicAlias=0, subscriptionIdentifiers=[]}.
No publish flow registered for MqttStatefulPublish{stateless=MqttPublish{topic=test/topic, payload=3byte, qos=AT_LEAST_ONCE, retain=false}, packetIdentifier=7, dup=false, topicAlias=0, subscriptionIdentifiers=[]}.
No publish flow registered for MqttStatefulPublish{stateless=MqttPublish{topic=test/topic, payload=3byte, qos=AT_LEAST_ONCE, retain=false}, packetIdentifier=8, dup=false, topicAlias=0, subscriptionIdentifiers=[]}.

**Comment by wenyanwen** [comment]
The code above implements this style

**Comment by SgtSilvio** [comment]
Now I understand what you are asking for.

With the blocking API you have to receive the messages in a loop in your own thread, for example:
```java
try (Mqtt3Publishes publishes = client.publishes(MqttGlobalPublishFilter.ALL)) {
    while (true) {
        Mqtt3Publish publish = publishes.receive();
        log.info("{}", publish);
    }      
} catch (Exception e) {
    log.error("err", e);
}
```
I would suggest using the async API with a callback:
```java
client.toAsync().subscribeWith()
        .topicFilter("test/topic")
        .qos(MqttQos.EXACTLY_ONCE)
        .callback(publish -> log.info("{}", publish))
        .send()
```

**Comment by wenyanwen** [comment]
How does the asynchronous API take it as an object

**Comment by wenyanwen** [comment]
How does the asynchronous API convert each of its data stores into an object

**Comment by SgtSilvio** [comment]
> How does the asynchronous API convert each of its data stores into an object

I do not understand your question? The asynchronous API has no "data stores"
