### ISSUE TITLE
My client keeps error reading the certificate

### ISSUE THREAD

**Issue by wenyanwen** [hivemq/hivemq-mqtt-client#351]
.keyManagerFactory(KeyStoreUtil.keyManagerFromKeystore(
                            new File("src/main/resources/ca/mqtt-client-key.pem"),
                            "changeme",
                            "changeme"))
                    .trustManagerFactory(KeyStoreUtil.trustManagerFromKeystore(
                            new File("src/main/resources/ca/mqtt-client-cert.pem"),
                            "changeme"))
                    .applySslConfig()

Not able to open or read KeyStore 'D:\IdeaProjects\testmqtt\src\main\resources\ca\mqtt-client-key.pem

**Comment by wenyanwen** [comment]
I generated the certificate following this link

https://www.hivemq.com/blog/end-to-end-encryption-in-the-cloud/

**Comment by SgtSilvio** [comment]
The `KeyStoreUtil` can only open key stores and not the certificates/keys directly.
A key store is a collection of keys and/or certificates.
For the client side this means:
- The key manager takes a key store that contains the key and certificate of the client.
- The trust manager takes a key store that contains the root certificates of the server's certificate chain.

For building a key store from individual certificates/keys you can take a look at the following code:
https://github.com/hivemq/mqtt-cli/blob/develop/src/main/java/com/hivemq/cli/commands/AbstractCommonFlags.java#L235
