### ISSUE TITLE
async client blocked when trying to re-subscribe when HiveMQ Server restarted.

### ISSUE THREAD

**Issue by endevcy** [hivemq/hivemq-mqtt-client#352]
## Expected behavior
Async client can resubscribe after reconnection.
## Actual behavior
Async client seems to be blocked.

## To Reproduce
```
import com.hivemq.client.mqtt.MqttClientState;
import com.hivemq.client.mqtt.datatypes.MqttQos;
import com.hivemq.client.mqtt.lifecycle.MqttClientConnectedContext;
import com.hivemq.client.mqtt.lifecycle.MqttClientConnectedListener;
import com.hivemq.client.mqtt.lifecycle.MqttClientDisconnectedContext;
import com.hivemq.client.mqtt.lifecycle.MqttClientDisconnectedListener;
import com.hivemq.client.mqtt.mqtt3.Mqtt3BlockingClient;
import com.hivemq.client.mqtt.mqtt3.Mqtt3Client;
import com.hivemq.client.mqtt.mqtt3.message.connect.Mqtt3Connect;
import com.hivemq.client.mqtt.mqtt3.message.publish.Mqtt3Publish;
import com.hivemq.shaded.org.jetbrains.annotations.NotNull;
import lombok.extern.slf4j.Slf4j;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;

@Slf4j
public class MqttConnector implements MqttClientConnectedListener, MqttClientDisconnectedListener {

    private final String host;
    private final int port;

    private Mqtt3BlockingClient client;
    private Mqtt3Connect connectConfig;

    private Map<String, Consumer> subscriptionMap = new HashMap<>();

    public MqttConnector(String host, int port) {
        this.host = host;
        this.port = port;
        this.client = buildClient();
        this.connectConfig = buildConnectionConfig();
    }

    private Mqtt3BlockingClient buildClient() {
        return Mqtt3Client.builder()
                .identifier("id#" + UUID.randomUUID().toString())
                .serverHost(host)
                .serverPort(port)
                .automaticReconnect()
                .initialDelay(500, TimeUnit.MILLISECONDS)
                .maxDelay(30, TimeUnit.SECONDS)
                .applyAutomaticReconnect()
                .addConnectedListener(this)
                .addDisconnectedListener(this)
                .buildBlocking();
    }

    private Mqtt3Connect buildConnectionConfig() {
        return Mqtt3Connect.builder().cleanSession(true).build();
    }

    void connect() {
        String mqttBroker = this.host + ":" + this.port;
        try {
            client.connect(connectConfig);
        } catch (Exception e) {
            log.error("Couldn't establish connection to MQTT broker: " + mqttBroker, e);
        }
    }

    public boolean subscribe(String topic, Consumer consumer) {
        try {
            client.toAsync()
                    .subscribeWith()
                    .topicFilter(topic)
                    .callback(consumer)
                    .send()
                    .get();
            log.info("Successfully subscribed to topic: " + topic);

            subscriptionMap.putIfAbsent(topic, consumer);
            return true;
        } catch (InterruptedException | ExecutionException e) {
            log.error("Could not subscribe to topic '" + topic + "'", e);
            return false;
        }
    }

    @Override
    public void onConnected(@NotNull MqttClientConnectedContext mqttClientConnectedContext) {

        if (!subscriptionMap.isEmpty()) {
            subscriptionMap.forEach(this::subscribe);
        }
    }

    @Override
    public void onDisconnected(@NotNull MqttClientDisconnectedContext mqttClientDisconnectedContext) {
    }
}
```

### Steps
1. start HiveMQ server on docker.
2. mqtt3 client subscribe some topics and save this information on Hashmap.
3. restart HiveMQ container ( to mimic unexpected server break )
4. mqtt3 client disconnected and connected again ( because of automaticReconnect config)
5. if Hashmap contains topic information, call subscribe to resubscribe.
6. blocked.

### Reproducer code
See the above code

## Details
- Affected HiveMQ MQTT Client version(s): 1.1.0
- Used JVM version: java version "13.0.1"

**Comment by endevcy** [comment]
And the consumer looks like
`
    class BizConsumer implements Consumer<Mqtt3Publish> {

        @Override
        public void accept(Mqtt3Publish mqtt3Publish) {
            log.debug(mqtt3Publish.toString());
        }
    }
`

**Comment by endevcy** [comment]
FYI, when I debugged into source codes, 

at first subscription, MqttSubscriptionHandler.java file's line 124, which start like

`   @CallByThread("Netty EventLoop")
    @Override
    public void run() {
        if (!hasSession) {
            clearQueued(MqttClientStateExceptions.notConnected());
            return;
        }
       ....
`

was called. 

But after reconnection and trying to resubscription, that run() method was not called.

And when I tried with client.toRx(). subscribeStream()....  resubscription worked well. It would be good to have a way of using async client or if not, I want to know why async client doesn't work.

**Comment by SgtSilvio** [comment]
You call `get()` on the returned Future of `subscribe`.
Calling `get` waits for the Future to complete, so your subscribe method is not asynchronous and would be the same when using the blocking API.
You are not allowed to block in Connected/DisconnectedListeners as stated in the javadoc.

Example for handling the subscribe call asynchronous:
```java
client.toAsync().subscribeWith()
        .topicFilter(topic)
        .callback(consumer)
        .send()
        .whenComplete((subAck, error) -> {
            if (error == null) {
                log.info("Successfully subscribed to topic: " + topic);
            } else {
                log.error("Could not subscribe to topic: " + topic, error);
            }
        });
```

**Comment by endevcy** [comment]
thanks. If you don't mind, let me ask a question.
One thing I can't understand is that why then at first subscribe() method call doesn't block? I mean, when I debugged much time, the first subscribe call always was not blocked.

**Comment by SgtSilvio** [comment]
@endevcy 
The `get` method call blocks always.
I copied your code above and can reproduce that it always blocks when adding entries to the subscriptionMap.
I do not know how you fill the subscriptionMap, but I would guess that on first connect you perform subscribe differently and the subscriptionMap is empty, so `get` is not called inside the `ConnectedListener`

**Comment by endevcy** [comment]
@SgtSilvio  Thank you for your detailed explanation. Yes, the subscribe method is called at first outside the ConnectedListener. Maybe that's why I got stuck. Thank you.
