### ISSUE TITLE
Problems connecting to Server using wss communication protocol - A code example is needed

### ISSUE THREAD

**Issue by bbd025** [hivemq/hivemq-mqtt-client#353]
**Expected**: In my Android app, connect to server using wss protocol with Reactive api: configuring server address, port and transport configuration(wss).

**Actual**: The problem is I cannot connect to the requested server. I am getting " com.hivemq.client.mqtt.exceptions.ConnectionFailedException: java.net.URISyntaxException: Expected closing bracket for IPv6 address at index 33: ws://[MY_SERVER_ADDRESS]:80/"

### Reproducer code

val client = MqttClient
                            .builder()
                            .serverHost(MY_SERVER_ADDRESS)
                            .identifier(clientId)
                            .useMqttVersion3() 
                            .addDisconnectedListener {
// getting this error when subscribe to this client
                                android.util.Log.d("MY_TAG","addDisconnectedListener -cause: ${it.cause}")
                            }
                            .webSocketConfig()
                            .applyWebSocketConfig()
                            .automaticReconnect()
                            .applyAutomaticReconnect()
                            .buildRx()

Note:
1. I tried to use transportConfig(transportConfig) on my MqttClient.builder() - but still got an exception ("unable to resolve host")
2. I tried to create my own address:
val address = InetSocketAddress(MY_SERVER_ADDRESS, 443) - but still no luck.
3. I tried to configure my own web socket configuration - but got a connection error.

Additional info:
connecting to my MY_SERVER through MQTTBox (http://workswithweb.com/mqttbox.html) worked.

I will appreciate a simple code example of how to connect to server with wss.

## Details
- Affected HiveMQ MQTT Client version(s): 
hivemq-mqtt-client-shaded', version: '**1.1.3**'
- Used JVM version:
1.8

**Comment by SgtSilvio** [comment]
Hi @bbd025 
If you want to use secure websockets, then you have to use both websockets and ssl/tls:
```java
Mqtt3Client.build()
        ...
        .webSocketWithDefaultConfig()
        .sslWithDefaultConfig()
        ...
```
If you want to customize the websocket path you have to specify it in the websocket config:
```java
Mqtt3Client.build()
        ...
        .webSocketConfig()
            .serverPath("mqtt")
            .applyWebsocketConfig()
        .sslWithDefaultConfig()
        ...
```
`serverHost` only takes the host part of the websocket url, without any "wss://" or any path
