### ISSUE TITLE
How do I configure the code to retrieve incoming response messages?

### ISSUE THREAD

**Issue by GeorgeMina** [hivemq/hivemq-mqtt-client#360]
### Reproducer code

```java
public void subscribe(Mqtt3AsyncClient client, String topic, byte qos) {
    client.subscribeWith()
            .topicFilter(topic)
            .callback(publish -> {
                //Do something
                Log.d(CLASS_NAME, publish.getTopic().toString());
            })
            .send()
            .whenComplete((subAck, throwable) -> {
                if (throwable != null) {
                    Log.d(CLASS_NAME, "Subscription failed..");
                } else {
                    Log.d(CLASS_NAME, "Subscription successful!");
                }
            });
}
```

## Details
- Affected HiveMQ MQTT Client version(s): 
- Used JVM version:

Apologies for turning here, but I really have no-where else to search.

What am I meant to put in the //Do something block in order to retrieve messages sent from the broker? What I have right now does not output "publish.getTopic().toString()" to the log, although connect, publish and subscribe all work.

**Comment by SgtSilvio** [comment]
Hi @GeorgeMina 
If I understand correctly, your callback is not called and you ask why it is not called.
You have to publish to the topic after you subscribed to the topic. Then the callback is called.

**Comment by GeorgeMina** [comment]
Dear @SgtSilvio,
Firstly thanks for the prompt response. 
So first I subscribe to this topic "/xxx/xxxxxxxxxx/response/" like so:

`public void subscribe(Mqtt3AsyncClient client, String topic, byte qos) {
        client.subscribeWith()
                .topicFilter(topic)
                .callback(publish -> {
                    //Do something

                    Log.d(CLASS_NAME, publish.getTopic().toString());
                })
                .send()
                .whenComplete((subAck, throwable) -> {
                    if (throwable != null) {
                        Log.d(CLASS_NAME, "Subscription failed..");
                    } else {
                        Log.d(CLASS_NAME, "Subscription successful!");
                    }
                });
    }`

(Although I am not using 'qos' anywhere - I was hoping that wasn't an issue).

Then, I publish to topic "/xxx/xxxxxxxxxx/request/" like so:

`private void publish(Mqtt3AsyncClient client, String topicPub, JSONObject jsonObject) {
        // Publish to the server
        client.publishWith()
                .topic(topicPub)
                .payload(jsonObject.toString().getBytes(StandardCharsets.UTF_8))
                .qos(MqttQos.EXACTLY_ONCE)
                .send()
                .whenComplete((mqtt3Publish, throwable) -> {
                    if (throwable != null) {
                        // Handle failure to publish
                        Log.d(CLASS_NAME, "Publish failed..");
                    } else {
                        // Handle successful publish, e.g. logging or incrementing a metric
                        Log.d(CLASS_NAME, "Publish successful!");
                    }
                });`

Then I use buttons to call the subscribe/publish methods:
                 publish(client, topicPub, jsonObject);
                 subscribe(client, topicSub, (byte) 0);

I get the success messages printed on my output log. However, in the subscribe() method, .callback() does not seem to be entered.

I know that the broker and topics work, because MQTTBox can publish & get responses properly.

What am I missing here?

**Comment by GeorgeMina** [comment]
Small update: I noticed my client is disconnected right after connecting, although I remain in the same activity. Is that expected behaviour, or it is meant to stay connected?

**Comment by SgtSilvio** [comment]
Please add a disconnected listener to the client and paste the log:
```java
Mqtt3Client.builder()
        ...
        .addDisconnectedListener(context -> Log.d(context.getCause()))
        .build()
```

**Comment by SgtSilvio** [comment]
If you publish to "/xxx/xxxxxxxxxx/request/" and subscribe to "/xxx/xxxxxxxxxx/response/" it is clear that you do not get any messages.
You have to publish to the same topic where your subscribe to.

**Comment by GeorgeMina** [comment]
Many thanks, I need to look into the available tools for debugging. getCause() returns the below message:

2019-12-20 13:37:00.213 4080-4122/com.example.smartbox D/DEBUG: com.hivemq.client.mqtt.exceptions.ConnectionClosedException: Server closed connection without DISCONNECT.

**Comment by GeorgeMina** [comment]
Even if I subscribe/publish to the same topic, callback() is not entered. Client disconnects after doing either a publish or subscribe. Perhaps there's something fundamentally wrong with my code.

**Comment by GeorgeMina** [comment]
@SgtSilvio Apparently my issue was caused because I was not using a unique client ID for my devices. Once I put generateClientID(), the client remained connected and responses were received as expected. 

Now I can either leave this question for reference, or delete it.

**Comment by SgtSilvio** [comment]
Nice to hear that you got it resolved.
Just leave the question.
