### ISSUE TITLE
Reconnection is not successful with ActiveMQ broker with MQTT enabled.

### ISSUE THREAD

**Issue by dileepmandapam** [hivemq/hivemq-mqtt-client#361]
## Expected behavior
Automatic reconnect with default config should be successful.
## Actual behavior
Frequent connections and disconnections are happening every minute. But when tested with hive test broker its working fine.
### Steps
Introduced temporary network glitch.
### Reproducer code
```java
   final @NotNull Mqtt3AsyncClient mqtt3AsyncClient = Mqtt3Client.builder().identifier(UUID.randomUUID().toString())
                .sslWithDefaultConfig()
                .serverHost("queue-eu1.xyz.com")
                .serverPort(8883)
                .automaticReconnectWithDefaultConfig()
                .addConnectedListener(new MqttClientConnectedListener() {
                    @Override
                    public void onConnected(@NotNull MqttClientConnectedContext context) {
                        System.out.println("Connected : " + context.toString() + " at : " + Instant.now());
                    }
                })
                .addDisconnectedListener(new MqttClientDisconnectedListener() {
                    @Override
                    public void onDisconnected(@NotNull MqttClientDisconnectedContext context) {
                        System.out.println("Disconnected : " + context.getCause() + " at : " + Instant.now());
                    }
                })
                .simpleAuth().username("xxxx@yy.com").password("password123123".getBytes()).applySimpleAuth()
                .buildAsync();
        System.out.println("Client state : " + mqtt3AsyncClient.getState());
        mqtt3AsyncClient.connectWith().cleanSession(false).send().whenComplete(((mqtt3ConnAck, throwable) -> {
            if (throwable != null) {
                System.out.println("Connection Failed : " + throwable);
            } else {
                System.out.println("Connect with completed." + mqtt3ConnAck);
            }
        })).join();
        //subscribe
        mqtt3AsyncClient.toAsync().subscribeWith()
                .topicFilter("ece5a29f-212e-460c-a60e-1a0484aaf5aa/xyz/state")
                .callback(mqtt3Publish -> System.out.println("mqtt3Publish : " + mqtt3Publish))
                .send()
                .whenComplete((mqtt3SubAck, throwable) -> {
                    if (throwable != null) {
                        System.out.println("Failed : " + throwable);
                    } else {
                        System.out.println("Subscription completed : " + mqtt3SubAck.toString());
                    }
                });
```
## Details
I have an ActiveMQ broker with MQTT enabled. My client is using a hive MQTT java library for event subscription. Establishing persistent connection
     
- Affected HiveMQ MQTT Client version(s): hivemqtt-client-shaded-1.1.3
- Used JVM version:
DileepMapamsMBP:mqttsamples dmandapam$ java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_192-b12)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.192-b12, mixed mode)
DileepMapamsMBP:mqttsamples dmandapam$ 

Also how to enable hive MQTT client logs?

**Comment by SgtSilvio** [comment]
Hi @dileepmandapam 

What do you mean with:

> Automatic reconnect with default config should be successful.

Are you not able to reconnect at all or are you just observing frequent reconnections?

> Also how to enable hive MQTT client logs?

The HiveMQ MQTT Client uses slf4j for logging, so you need to add a logging library, for example logback http://logback.qos.ch/
I think that the logs of the client will not help with your problems. What is the cause of the DisconnectedListener?
Did you check the logs of ActiveMQ? As it does not happen with HiveMQ I suspect ActiveMQ to be the cause of the problem.

**Comment by SgtSilvio** [comment]
Closed because of inactivity.
Feel free to comment and reopen.

**Comment by ramod8** [comment]
@dileepmandapam Are you still encountering this error?
