### ISSUE TITLE
client threads are not released even after disconnect

### ISSUE THREAD

**Issue by dileepmandapam** [hivemq/hivemq-mqtt-client#366]
Hi,
Below client threads are not released after disconnect is invoked. How to shutdown client gracefully? 

> RxCachedWorkerPoolEvictor-1
> RxComputationThreadPool-1
> RxComputationThreadPool-2
> RxSchedulerPurge-1

Thanks
Dileep.

**Comment by SgtSilvio** [comment]
Hi @dileepmandapam 
These threads are daemon threads created by RxJava and not by the client. You do not have to worry about them. The client shuts down all of its own threads automatically.

If you really want to shutdown these threads (again: this is unnecessary as they are daemon threads) the question was already answered in #314

**Comment by dileepmandapam** [comment]
Hi @SgtSilvio 
Thanks for your info. But the current use-case is, multiple MQTT clients, connect to different brokers. I need to shutdown each MQTT client gracefully. That's where I am seeing the issue of leaking Rx threads. I think we cannot use Schedulers.shutdown().

**Comment by dileepmandapam** [comment]
Hi @SgtSilvio ,
I ran a quick test by creating 100 clients. The Rx threads are capped to 8 only. 

Thanks 
Dileep
