### ISSUE TITLE
No news for consumption

### ISSUE THREAD

**Issue by 52HZWU** [hivemq/hivemq-mqtt-client#367]
[com.hivemq.client.mqtt-1-1] WARN com.hivemq.client.internal.mqtt.handler.publish.incoming.MqttIncomingPublishService - No publish flow registered for MqttStatefulPublish{stateless=MqttPublish{topic=testmqtt10, payload=5byte, qos=EXACTLY_ONCE, retain=false}, packetIdentifier=6, dup=false, topicAlias=0, subscriptionIdentifiers=[1]}.

Look at the problem

**Comment by SgtSilvio** [comment]
The message means that the client received a message, but you did not register a callback and therefore the message is dropped.

**Comment by 52HZWU** [comment]
Thank you for your answer，How can i proceed registration callback

**Comment by SgtSilvio** [comment]
Example to register a callback for a single subscription with the async API:
```java
client.toAsync().subscribeWith()
        .topicFilter("test/topic")
        .qos(MqttQos.AT_LEAST_ONCE)
        .callback(publish -> {
            // callback code
        })
        .send();
```
Example to register a callback for all received messages with the async API:
```java
client.toAsync().publishes(MqttGlobalPublishFilter.ALL, publish -> {
    // callback code
});
```
