### ISSUE TITLE
Consumption data lost

### ISSUE THREAD

**Issue by 52HZWU** [hivemq/hivemq-mqtt-client#368]
Publish and subscribe clients can be consumed at the same time.
However, after using the session for caching, the subscription client goes offline and goes online again, and the message is lost.
The error warning is:
[com.hivemq.client.mqtt-1-1] WARN com.hivemq.client.internal.mqtt.handler.publish.incoming.MqttIncomingPublishService - No publish flow registered for MqttStatefulPublish{stateless=MqttPublish{topic=testmqtt10, payload=5byte, qos=EXACTLY_ONCE, retain=false}, packetIdentifier=6, dup=false, topicAlias=0, subscriptionIdentifiers=[1]}.

How to register callback？

Subscription code：
![image](https://user-images.githubusercontent.com/53888910/73709094-1dfd3f00-473b-11ea-84f3-fd4d2ad06185.png)

publish code：
![image](https://user-images.githubusercontent.com/53888910/73709133-38cfb380-473b-11ea-95e8-8de565b31325.png)

**Comment by 52HZWU** [comment]
Subscription code：
<img width="947" alt="Subscription" src="https://user-images.githubusercontent.com/53888910/73709391-e9d64e00-473b-11ea-8e78-cec938ec0a92.png">

publish code：
<img width="1011" alt="publish" src="https://user-images.githubusercontent.com/53888910/73709409-f35fb600-473b-11ea-912b-4da1c206fb7c.png">

**Comment by SgtSilvio** [comment]
If you connect your subscriber the second time when you already have a session, the server already knows the subscription and starts sending messages to the client.
You register the callback too late when you subscribe for the second time.
Try adding the callback before you connect the client.
To do this add the following code before the `client.connectWith...` in your subscriber:
```java
client.toAsync().publishes(MqttGlobalPublishFilter.ALL, publish -> {
    // callback code
});
```
