### ISSUE TITLE
lost QoS2 messages after a failure

### ISSUE THREAD

**Issue by freyssin** [hivemq/hivemq-mqtt-client#378]
We have a client that subscribes on a topic with QoS2 in a durable session (cleanSession= false). This client uses the HiveMQ blocking API with automatic reconnection feature. This test works correctly in the absence of failure, but the subscriber loses messages after stopping and restarting the server.

## Expected behavior

We expect that the client reconnects to the server and continues to receive messages (no loss, no duplication).

## Actual behavior

The client reconnects to the server but loses a sequence of messages. According to the network capture (see below), these messages are well received and acknowledged, but they are not delivered to the client.

## Detailed execution

Below the initialization code of the subscriber:
```
Mqtt3Client.builder()`
      .identifier(clientid)
      .serverHost(uri.getHost())
      .serverPort(uri.getPort())
      .automaticReconnectWithDefaultConfig()
      .addDisconnectedListener(context -> context.getCause().printStackTrace())
      .buildBlocking()
client.connectWith().cleanSession(false).send();
```
and the code of the listener thread:
```
while (true) {
  try (Mqtt3BlockingClient.Mqtt3Publishes publishes = client.publishes(MqttGlobalPublishFilter.ALL)) {
    Mqtt3Publish msg = publishes.receive();
    byte[] payload = msg.getPayloadAsBytes();
    // Print the message number
    handleMessageArrived(msg.getTopic().toString(), payload, 0, payload.length);
  } catch (InterruptedException e) {
    e.printStackTrace();
  }
}
```

In the table below we reproduce the sequence of messages before and after the disconnection (the wireshark capture of this sequence is attached). As explained below it seems that the problem comes from the takeover of the client.

  | Server (frames sent) | Client (Frames sent) | Client (stdout)
-- | -- | -- | --
565 | PUBLISH #39 |   |  
566 |   | PUBREC #39 | msg#39
571 | PUBREL #39 |   |  
572 |   | PUBCOMP #39 |  
  | == stop/restart == | == stop/restart == |  
715 |   | CONNECT |  
717 | CONNACK |   |  
719 | PUBLISH #40, #41, #42, #43, #44, #45, #46, #47 |   |  
722 | PUBLISH #48 |   |  
724 |   | PUBREC #40, #41, #42, #43, #44, #45, #46, #47 | msg#40
725 |   | PUBREC #48 | msg#48
730 | PUBREL #40 |   |  
731 |   | PUBCOMP #40 |  
733 | PUBLISH #41, #42, #43, #44, #45, #46, #47, #48 |   |  
  |   | PUBCOMP #41, #42, #43, #44, #45, #46, #47, #48 |  
737 | PUBLISH #49 |   |  
738 |   | PUBREC #49 | msg#49
744 | PUBREL #49 |   |  
745 |   | PUBCOMP #49 |  

1. Before the failure, message #39 is received by the client and correctly acknowledged.
2. After the failure, the server sends accumulated messages (#40 to #47) in a unique TCP packet, then message #48.
3. Only the first message of TCP Packet 719 (#40) seems to be delivered to the client. Messages #41 to #47 have disappeared.
4. Then everything seems to work fine.

[hivemq-lost-filtered.zip](https://github.com/hivemq/hivemq-mqtt-client/files/4260349/hivemq-lost-filtered.zip)

## Details
- Affected HiveMQ MQTT Client version(s): improvement~memory-improvements-SNAPSHOT 
- Used JVM version:
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

**Comment by clive-jevons** [comment]
Hey there,

Sounds very similar to a behaviour I'd observed in some of my tests - and in my case it was because I had a misconception about persistent subscriptions. They are bound to a server session, so if after the reconnect the session is gone (because the server was a single-node, non-clustered and didn't have any kind of persistence configured), then the subscriptions are not renewed, because as far as both client and server is concerned it's a completely new session.

In my test setup I was using docker-compose and initially was stopping and starting the HiveMQ container. This caused loss of subscriptions. When I paused and unpaused the container instead, the server didn't loose the session information and was able to re-establish the subscriptions.

I believe there's also another issue on here somewhere where this behaviour is being discussed (e.g. add a property which can be set so that the client will auto-recreate subscriptions for a new session after a reconnect).

HTH
Cheers,
C

**Comment by SgtSilvio** [comment]
Hi @freyssin 
You have to register the publishes object once not in the while loop.
You should also register it before the connect call.
Something like the following:
```java
try (Mqtt3BlockingClient.Mqtt3Publishes publishes = client.publishes(ALL)) {
    client.connectWith().cleanSession(false).send();
    while (true) {
        Mqtt3Publish msg = publishes.receive();
    }
}
```

**Comment by SgtSilvio** [comment]
@freyssin Feel free to comment if this solved your problem or if you have additional questions

**Comment by freyssin** [comment]
Indeed the error was in my code :-(, now everything is perfect.
Thank you so much.
