### ISSUE TITLE
Disconnection - reconnection loop

### ISSUE THREAD

**Issue by lukkna** [hivemq/hivemq-mqtt-client#382]
I'm using hivemq client (1.1.3-1.1.4) on my android app which is used on android 9 devices with cellular internet connection (mostly 4g, sometimes 3g).
Some of the users informed me that devices sometimes receives messages with delay (from couple minutes to 20+ minutes). I've inspected mosquitto (1.6.8) logs and noticed that said clients stop sending ping requests and start disconnecting-reconnecting (in some cases such loop continues for 2 hours).
I have around 50-60 clients connected to my mosquitto broker, each client receives up to 100 messages per day (up to 10 to one topic, and up to 100 to another topic), mqtt - 3.1.1. Keep alive is set to 60 secs.
Also I've faced an issue where mosquitto would send a message to client, client would acknowledge that he received it and yet from google analytics I could see that client didn't actually receive a message. Checking mosquitto logs I'd see that right after sending or before sending message, client would disconnect-reconnect multiple times.
Adding screenshot of said mosquitto logs with client id blurred out (it's the same client over all of this log).
I can add any additional information you might need.
[logs](https://i.imgur.com/9Hiidhd.png)

**Comment by SgtSilvio** [comment]
Hi @lukkna 
We have not seen this behavior before.
Does it occur with both versions 1.1.3 and 1.1.4 ?
Could you share your client code or parts of it?

**Comment by lukkna** [comment]
Yes, both versions.

Building client:
`    private Mqtt3RxClient buildClient(MqttConfig config, String imei) {
        return MqttClient.builder()
                .useMqttVersion3()
                .identifier("ePCR mobile-" + imei)
                .serverHost(config.getHost())
                .serverPort(config.getPort())
                .automaticReconnectWithDefaultConfig()
                .simpleAuth()
                .username(config.getUsername())
                .password(config.getPassword().getBytes())
                .applySimpleAuth()
                .addConnectedListener(this)
                .addDisconnectedListener(this)
                .buildRx();
    }`

Connecting:
`    private void connect() {
        client.connectWith()
                .keepAlive(60)
                .cleanSession(false)
                .applyConnect()
                .retry()
                .doOnError(e -> Timber.e(e, "MQTT failed to connect."))
                .subscribeOn(schedulerProvider.io())
                .observeOn(schedulerProvider.io())
                .doOnEvent(this::logResult)
                .subscribe();
    }`

Subscribing:
`    private Observable<String> getSubObservable(String topic) {
        return client.subscribeStreamWith()
                .topicFilter(topic)
                .qos(AT_LEAST_ONCE)
                .applySubscribe()
                .doOnSingle(subAck -> Timber.i("MQTT subscribed. Topic = [%s]", topic))
                .toObservable()
                .doOnDispose(() -> unsubscribe(topic))
                .doOnError(e -> Timber.e(e, "MQTT failed to subscribe. Topic = [%s]", topic))
                .filter(publish -> publish.getTopic().toString().equals(topic))
                .map(Mqtt3Publish::getPayloadAsBytes)
                .map(String::new)
                .doOnNext(id -> {
                    eventTracker.logTeamPcrsUpdateMessageReceived(id);
                    Timber.i("MQTT received message. Pcr id = [%s], topic = [%s]", id, topic);
                });
    }`

Unsubscribing:
`    private void unsubscribe(String topic) {
        client.unsubscribeWith()
                .topicFilter(topic)
                .applyUnsubscribe()
                .retry()
                .doOnError(e -> Timber.e(e, "MQTT failed to unsubscribe. Topic = [%s]", topic))
                .subscribeOn(schedulerProvider.io())
                .observeOn(schedulerProvider.io())
                .subscribe();
    }`

**Comment by SgtSilvio** [comment]
Could you reproduce this and provide a wireshark capture of the packet exchange?

**Comment by lukkna** [comment]
Sorry for the delay. I'll do this next week.

**Comment by SgtSilvio** [comment]
Hi @lukkna 
Are you still seeing this behavior.
Could this have something to do with Android sleep modes?

**Comment by lukkna** [comment]
Sorry, I've forgot to reply. I've turned off battery optimizations for the app. I solved the issue by adding foreground service with notification. Before that once screen is off, I would start getting disconnects.

**Comment by android-bash** [comment]
@SgtSilvio Yeah even i am facing this. Basically it disconnects every minute and reconnects. Any idea how we can stop this?

**Comment by lukkna** [comment]
@android-bash Easy way is to get wake lock on app start. To prevent android from denying wake lock when app goes to background, create foreground service with always visible notification.
