### ISSUE TITLE
maximumQosCode = 2 ,"wrong maximum Qos"!!

### ISSUE THREAD

**Issue by Gavinwgq** [hivemq/hivemq-mqtt-client#389]
Mqtt5ConnAckDecoder.java

> final short maximumQosCode = unsignedByteOnlyOnce(maximumQosPresent, "maximum Qos", in);
                    if (maximumQosCode != 0 && maximumQosCode != 1) {
                        throw new MqttDecoderException(Mqtt5DisconnectReasonCode.PROTOCOL_ERROR, "wrong maximum Qos");
                    }

when maximumQosCode = 2, throw Exception 
why?

- Affected HiveMQ MQTT Client version(s):  1.1.4
- Used JVM version:1.8

**Comment by SgtSilvio** [comment]
According to the MQTT 5 specification:

> Followed by a Byte with a value of either 0 or 1. It is a Protocol Error to include Maximum QoS more than once, or to have a value other than 0 or 1. If the Maximum QoS is absent, the Client uses a Maximum QoS of 2.

https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901084
