### ISSUE TITLE
Crash when using ProGuard

### ISSUE THREAD

**Issue by hoogendam** [hivemq/hivemq-mqtt-client#390]
When using Proguard with minifyEnabled true, the app crashes with the following error:

    java.lang.RuntimeException: java.lang.NoSuchFieldException: No field consumerIndex in class Lm/a/a/c; (declaration of 'm.a.a.c' appears in /data/app/9MnO7seqHfAMc0QleCSejA==/base.apk)
        at m.a.b.b.fieldOffset(:91)
        at m.a.a.c.<clinit>(:47)
        ... 154 more
    Caused by: java.lang.NoSuchFieldException: No field consumerIndex in class Lm/a/a/c; (declaration of 'm.a.a.c' appears in /9MnO7seqHfAMc0QleCSejA==/base.apk)
        at java.lang.Class.getDeclaredField(Native Method)
        at m.a.b.b.fieldOffset(:87)
        ... 155 more

I have narrowed this down to the instantiation of a Mqtt3AsyncClient. It worked fine before, but it seems that since I performed some upgrades (Android Studio 3.6.x, Gradle 5.6.4), it no longer works.

The underlying error seems to be caused by hivemq-mqtt-client's dependency on RxJava in combination with Proguard. I have tried adding Proguard rules for RxJava to my proguard-rules.pro but the crash still occurs.

    -keep class rx.schedulers.Schedulers {
        public static <methods>;
    }
    -keep class rx.schedulers.ImmediateScheduler {
        public <methods>;
    }
    -keep class rx.schedulers.TestScheduler {
        public <methods>;
    }
    -keep class rx.schedulers.Schedulers {
        public static ** test();
    }
    -keepclassmembers class rx.internal.util.unsafe.ArrayQueue*Field {
        long producerIndex;
        long consumerIndex;
    }
    -keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef {
        long producerNode;
        long consumerNode;
    }

## Details
- Affected HiveMQ MQTT Client version(s): 1.1.4
- Used JVM version: 1.8
- Used Gradle version: 5.6.4

**Comment by SgtSilvio** [comment]
Hi @hoogendam 
The documentation lists the necessary proguard rules: https://hivemq.github.io/hivemq-mqtt-client/docs/installation/android/
Please comment if this solved your problem.

**Comment by hoogendam** [comment]
Hi @SgtSilvio
I have used the hivemq-mqtt-client for several months in combination with ProGuard. The rules according to the documentation are there and used to work. However, I am now experiencing a crash. This is the configuration:

build.gradle

    minifyEnabled true
    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

proguard-rules.pro

    -keepclassmembernames class io.netty.** { *; }
    -keepclassmembernames class org.jctools.** { *; }

**Comment by SgtSilvio** [comment]
Hi @hoogendam 
I could reproduce your problem with a newly created Android app.
It seems that the new Android build version has different proguard behaviour.
The following proguard rules work for me (the second line changed):
```
-keepclassmembernames class io.netty.** { *; }
-keepclassmembers class org.jctools.** { *; }
```
Please remove the proguard rules you pasted above for RxJava, as they are for RxJava 1, but we use RxJava 2 which does not need self defined proguard rules.

I will update the documentation: https://hivemq.github.io/hivemq-mqtt-client/docs/installation/android/
Thank you for the report.
Please comment if the new rules also fix the problem on your side.

**Comment by hoogendam** [comment]
Hi @SgtSilvio 
Indeed, this has fixed the problem. Thanks!

**Comment by degill** [comment]
Hey @SgtSilvio :)

I am sorry for hijacking this thread, but it fits an observation of mine.

I had the exact same issue as the OP and your updated ProGuard rules fixed that for me (as a tiny note, maybe you could update this [blog post](https://www.hivemq.com/blog/hivemq-mqtt-client-features/android-support/)).

After fixing that I noticed that some other classes are missing, namely `java.lang.NoClassDefFoundError: io.netty.util.ReferenceCountUtil`:

```
io.netty.channel.AbstractChannelHandlerContext: An exception was thrown by a user handler while handling an exceptionCaught event
    java.lang.NoClassDefFoundError: io.netty.util.ReferenceCountUtil
        at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:87)
        at io.netty.channel.DefaultChannelPipeline.onUnhandledInboundUserEventTriggered(DefaultChannelPipeline.java:1218)
        at io.netty.channel.DefaultChannelPipeline$TailContext.userEventTriggered(DefaultChannelPipeline.java:1286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
        at com.hivemq.client.internal.mqtt.handler.MqttConnectionAwareHandler.userEventTriggered(MqttConnectionAwareHandler.java:43)
```

When I change `-keepclassmembernames class io.netty.** { *; }` to be `-keepclassmembers class io.netty.** { *; }` it seems to work fine then.

Does that rule have to be adjusted in the docs as well?
-------------
Affected HiveMQ MQTT Client version(s): 1.2.1
Android Build Tools version: 29.0.3
compileSdkVersion: 29
