### ISSUE TITLE
Persistant Storage and Message Redelivery

### ISSUE THREAD

**Issue by android-bash** [hivemq/hivemq-mqtt-client#391]
I am using HiveMq Client and i wanted to know how Message Redelivery works If client is offline and gets reconnected later, how will the messages published be stored? Is it in memory or file based storage? 

This is how i am publishing : 

    CompletableFuture<Mqtt3Publish> publishResultFuture = mClient.publishWith()
                            .topic(topic)
                            .payload(payload.getBytes())
                            .qos(MqttQos.EXACTLY_ONCE)
                            .retain(false)
                            .send();

                    publishResultFuture.whenComplete((publish, throwable) -> {
                        if (throwable == null) {
                            doAfterPublishSuccess(publish.getTopic().toString(), new 
    String(publish.getPayloadAsBytes()));
                        } else {
                            throwable.printStackTrace();
                        }
                    });

**Comment by SgtSilvio** [comment]
Hi @android-bash 
Currently messages are stored in memory so messages are redelivered when the client was offline and reconnects while the client application is still running.
For version 1.2 we are working on a persistence concept (#305 ) that enables a persistence restart of client applications.
Please comment if you have additional questions.

**Comment by android-bash** [comment]
Thanks for the reply. Could you please answer the following questions as well?
1. For now if i kill the client android application, the messages are lost? 
2. Is there any limit of messages that will be redelivered? 
3. Is it possible to clear those messages ourselves?

**Comment by android-bash** [comment]
@SgtSilvio Thanks for the reply. Could you please answer the following questions as well?

For now if i kill the client android application, the messages are lost?
Is there any limit of messages that will be redelivered?
Is it possible to clear those messages by ourselves?
Also any estimates on when Persistent storage build will be released?

**Comment by SgtSilvio** [comment]
Hi @android-bash 

Sorry for the late response. I did not see your comment here.

1. If you kill the client application, then messages that were not sent yet or were not fully processed yet are lost. Keep in mind that this would also be the case when you use a persistence, as messages also spend (more) time in your application code. With version 1.2 we will add a persistence concept and manual acknowledgement which will provide the best possible delivery guarantees.
1. Redelivery refers to inflight messages. As long as the session is not expired all inflight messages will be redelivered.
If you ask for queued/buffered messages:
For messages from the server to the client the amount of queued messages is defined by the broker.
For messages from the client to the server the amount of buffered messages is the receive maximum from the server and then backpressure is applied via the reactive API. For the async and blocking API an additional 64 messages are buffered before new calls to publish block (which is the only possibility for backpressure for the async and blocking API).
This behaviour will most likely change and get more configurable with 1.2
1. There is no API to clear buffered messages. Messages are cleared when the session expires.
1. I can not give you an exact date. You can track the progress via the milestone (https://github.com/hivemq/hivemq-mqtt-client/milestone/6) and the project (https://github.com/hivemq/hivemq-mqtt-client/projects/3)
