### ISSUE TITLE
When a disconnect occurs while subscribing to a topic the library blocks forever

### ISSUE THREAD

**Issue by mwalser** [hivemq/hivemq-mqtt-client#408]
We experienced problems with our application getting stuck occasionally. This was traced back to the HiveMQ MQTT Client library which appears to sometimes block forever when a disconnect occurs while subscribing to a topic.

An interesting observation is that we where only able to reproduce this problem with cleanSession set to false.

## Expected behavior
When two instances of the reproducer are run they cause each other to be disconnected since the same client identifier is used. This repeats forever.

## Actual behavior
After a few seconds one reproducer gets stuck attempting to subscribe to a topic:

```
[…]
Connect - Start
Connected listener called
Connect - Done
Subscribe - Start
Disconnected listener called
[No further output]
```

### Steps
- Open a console and run `docker run -it -p 1883:1883 eclipse-mosquitto:1.6.9`
- Run **two** instances of the reproducer program
- Observe one instance getting stuck after a few seconds

### Reproducer code
```
package reproducer;

import com.hivemq.client.mqtt.MqttClient;
import com.hivemq.client.mqtt.MqttClientState;
import com.hivemq.client.mqtt.mqtt3.Mqtt3Client;

public class Reproducer {
	private static final Mqtt3Client client = MqttClient.builder()
			.identifier("bug-reproducer")
			.addConnectedListener(context -> log("Connected listener called"))
			.addDisconnectedListener(context -> log("Disconnected listener called"))
			.useMqttVersion3()
			.serverHost("localhost")
			.serverPort(1883)
			.build();

	public static void main(String[] args) {
		while(true) {
			while(client.getState() == MqttClientState.CONNECTED) {
				// Busy wait until we are disconnected
			}

			connect();
		}
	}

	private static void connect() {
		try {
			log("Connect - Start");
			client.toBlocking().connectWith().cleanSession(false).send();
			log("Connect - Done");

			log("Subscribe - Start");
			client.toBlocking().subscribeWith().topicFilter("/topic").send();
			log("Subscribe - Done");
		} catch (Exception e) {
			log("Exception caught: "+e.getMessage());
		}
	}

	private static void log(String log) {
		System.out.println(log);
	}
}
```

## Details
- Affected HiveMQ MQTT Client version(s): 1.1.4
- Used JVM version: openjdk version "11.0.6" 2020-01-14

**Comment by SgtSilvio** [comment]
Hi @mwalser 
This behaviour is actually right, but your constellation of using persistent session without reconnect and using the blocking API does not make sense. Let me explain this.

The advantage of MQTT is to guarantee message delivery (depending on QoS) even if connections are intermittent. As long as an MQTT client has a session, the broker and the client hold state to resend pending messages once a connection is reestablished.
So as long as the client has a session, delivering messages with MQTT will never fail. You do not have to implement custom retries and custom deduplication.
The same also applies to subscribes or unsubscribes of the client. If the client has a session and you subscribe, but the connection is closed before the SUBACK was received the client will wait until the connection is reestablished to retry the SUBSCRIBE.
The problem with your example is that you are not reconnecting as you are waiting for the subscribe to finish; and the subscribe waits for a reconnect.

To resolve your issue just use automatic reconnect. It always is a good idea to use a reconnect strategy when using persistent sessions.
```java
MqttClient.builder()
        ...
        .automaticReconnectWithDefaultConfig()
        ...
```
(If you do not want to use the automatic reconnect feature, please separate connecting/disconnecting from publishing/subscribing)

Please comment if this makes sense to you.

**Comment by mwalser** [comment]
Hi @SgtSilvio,

thank you for your quick and extensive answer. I wasn't aware of this behavior, but it makes perfect sense.

We are currently not using the `automaticReconnectWithDefaultConfig()` feature since there are some requirements around the reconnect behavior that I believe are not able to be satisfied with this.
But I noticed that the `MqttClientDisconnectedContext` contains a `MqttClientReconnector`. So e might explore this avenue.

Again, thank you for your answer! I'm going to close the issue.
