### ISSUE TITLE
Setting a Session Expiry Interval to 0 during connection

### ISSUE THREAD

**Issue by freyssin** [hivemq/hivemq-mqtt-client#415]
If the Session Expiry Interval of the session is explicitely set to zero at connection time, the HiveMQ client sends a CONNECT packet in which the session expiration interval is not present.

This might seem correct since the specification says in the CONNECT section (3.1.2.11.2):
 - "If the Session Expiry Interval is absent the value 0 is used. If it is set to 0, or is absent, the Session ends when the Network Connection is closed".

However, in the section corresponding to the DISCONNECT (3.14.2.2.2) the specification indicates:
 - If the Session Expiry Interval is absent, the Session Expiry Interval in the CONNECT packet is used.
 - If the Session Expiry Interval in the CONNECT packet was zero, then it is a Protocol Error to set a non-zero Session Expiry Interval in the DISCONNECT packet sent by the Client.

Thus the specification specifies that the value of Session Expiry Interval can be overloaded in the DISCONNECT packet, but also that this overload can only be performed if the value in the CONNECT packet was not zero.

So I think it is a mistake to translate a value of 0 for the Session Expiry Interval as an absence of value in the CONNECT packet. With no value in the CONNECT, the overloading of the parameter is allowed in the DISCONNECT. By setting 0 in the CONNECT, the client explicitely forbids the overloading in the DISCONNECT. This part of the semantics is lost with the choice made in the Hive client.

**Comment by fraschbi** [comment]
Hi @freyssin ,

Thank you for input.
We will discuss this internally and get back to you.

Regards,
Florian

**Comment by SgtSilvio** [comment]
Hi @freyssin 
Interesting interpretation of the MQTT specification.
Nevertheless the intent of the specification is clear.
If the session expiry is 0 or is absent does not make a semantic difference, this is just about encoding. So the session expiry is treated as zero in both cases regardless if it is is encoded as 0 or if the encoding is omitted.

So "If the Session Expiry Interval in the CONNECT packet was zero" applies to a CONNECT packet which explicitly encoded the session expiry as 0 as well as to a CONNECT packet which omitted the encoding. If it would apply to the first case only the wording would have to be "was set to 0".
This also means your statement "With no value in the CONNECT, the overloading of the parameter is allowed in the DISCONNECT" is not correct.

Does this make sense to you?

**Comment by freyssin** [comment]
Hi,

I think you're right.

I think that the specification effectively makes it possible to interpret that the absence of "SessionExpiry Interval" value in the CONNECT packet is equivalent to a value 0. The assertion in the DISCONNECT section therefore also applies to the absence of "SessionExpiry Interval" value in CONNECT, and the additional case (no explicit value of "SessionExpiry Interval" in CONNECT) that I describe therefore does not exist.
It is therefore correct not to transfer the "SessionExpiry Interval" value into the CONNECT packet when it is zero.

thanks for these informations.
Regard, Andre.
