### ISSUE TITLE
ANR on Android when disconnecting the network for "too long"

### ISSUE THREAD

**Issue by H0RIA** [hivemq/hivemq-mqtt-client#416]
## Expected behavior
The client should not crash and reconnecting after a network down, when automatic reconnect is disabled should just leave the client in a "not connected" state.

## Actual behavior
The client, although not connected, when it tries to publish a message it crashes

## To Reproduce
I may be doing something wrong, but don't understand what...

broker: VerneMQ
mqtt version used: 5

### Steps
Android 8 AOSP

1. Wrap an mqqt async client instance in an Android service (sticky)
2. the mqtt connection does not use automatic reconnect
3. unplug network cable (for at about ~60 minutes)
4. reconnect the network cable (after ~60 minutes)
5. try to publish a message

-----

The mqtt client will become unresponsive and will crash after 1-2 minutes with the below stack trace. If the time for which the network is disconnected is less than about 40 minutes, this does not appear to happen.

### Reproducer code
This is the crash log:
 at java.lang.Object.wait(Native method)
  - waiting on <0x06659061> (a com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttPublishFlowables)
  at com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttPublishFlowables.add(MqttPublishFlowables.java:57)
  - locked <0x06659061> (a com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttPublishFlowables)
  at com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttAckSingle.subscribeActual(MqttAckSingle.java:57)
  at io.reactivex.Single.subscribe(Single.java:3575)
  at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
  at io.reactivex.Single.subscribe(Single.java:3575)
  at com.hivemq.client.internal.rx.RxFutureConverter$RxSingleFuture.<init>(RxFutureConverter.java:114)
  at com.hivemq.client.internal.rx.RxFutureConverter.toFuture(RxFutureConverter.java:44)
  at com.hivemq.client.internal.mqtt.MqttAsyncClient.publish(MqttAsyncClient.java:181)

## Details
- Affected HiveMQ MQTT Client version(s): 
1.1.4

- Used JVM version:

**Comment by SgtSilvio** [comment]
Hi @H0RIA 
To be able to help here, please answer the following questions

1. Do you use a session expiry > 0?
1. Can you give more detail about "try to publish a message", is it triggered by the user in the UI thread or in the background?
1. "does not use automatic reconnect", When do you reconnect?
1. "unplug network cable", Are you testing this on an Android emulator?

**Comment by H0RIA** [comment]
Hi Silvio,

Here are the client connect options:

client.connectWith()
                .cleanStart(true)
                .noSessionExpiry()
                .keepAlive(getKeepAlive())
                .restrictions()
                .receiveMaximum(8)
                .sendMaximum(16)
                .maximumPacketSize(4096)
                .sendMaximumPacketSize(4096)
                .topicAliasMaximum(16)
                .sendTopicAliasMaximum(8)
                .requestProblemInformation(true)
                .requestResponseInformation(true)
                .applyRestrictions()
                .send()
2. The first thing that usually happens in our context, after the network connect is back, is that another service pushes some data to the broker. 
3. There is a watchdog (alarm) triggered regularly. When network connectivity is back, the watchdog checks if the Android service (that wraps the mqtt client) is alive & connected. If not, it will: cleanup the client and restart the Android service.
4. Not on an emulator. It is a custom device.

**Comment by SgtSilvio** [comment]
@H0RIA 
My assumption: you are using QoS > 0 for publishing. Is that correct?

The async API can block on publish calls if you call if too often before the messages are acknowledged (this is a blocking backpressure mechanism, a non-blocking backpressure mechanism is implemented by the reactive API).
In your case I think the following happens:
- The connection of the client to the broker breaks but the client does not notice it yet
- You are still publishing messages which do not fail because the client thinks it is still connected
- All these messages are not acknowledged as the connection is actually broken
- You are probably calling publish around 100 times in this state and the last call blocks
- Since you have a persistent session (noSessionExpiry) the client does not fail the queued messages when it finally detects that the connection is lost, but instead waits until it is reconnected and then republishes the queued messages.
- It seems that you do not reconnect at all, so the last call to publish blocks some thread until Android finally decides to kill the application.

The solution would be to properly reconnect the client. Automatic reconnect will do that for you. Why are you not using it? You can customize when to reconnect in a DisconnectedListener.

Just a side note: Are you also using `cleanStart(true)` to reconnect? If you use a session expiry > 0 (`noSessionExpiry` means session expiry = infinity) you do not want to reconnect with cleanStart. This will cause queued messages to be cleared leading to the same effect as if the session expiry was 0.

Does this make sense to you? Are my assumptions correct?

**Comment by H0RIA** [comment]
Hi Silvio,

We had issues using automatic reconnect. I don't remember right now the exact context, but it seemed to cause problems. From what I remember, when the network was down for a longer period of time, it did not work properly. With short disconnects (a couple of minutes), it did work well though
Regarding the assumptions, they are partially correct. The one that is not is related to the QoS. We are using MqttQos.AT_MOST_ONCE (0). 

Once question I had is regarding the publish count. If the client is in the state you described, why would it matter if there are 100 or 1 messages to be published? I mean with 1, it should still cause the problem. Right?

I will try to use the automatic reconnect and also set the cleanStart to false. Thank you for your time!

**Comment by H0RIA** [comment]
I just tested with the automatic reconnect, and, unfortunately, I get the exact same error as before:

at java.lang.Object.wait(Native method)
  - waiting on <0x0c4d5492> (a com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttPublishFlowables)
  at com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttPublishFlowables.add(MqttPublishFlowables.java:57)
  - locked <0x0c4d5492> (a com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttPublishFlowables)
  at com.hivemq.client.internal.mqtt.handler.publish.outgoing.MqttAckSingle.subscribeActual(MqttAckSingle.java:57)
  at io.reactivex.Single.subscribe(Single.java:3575)
  at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
  at io.reactivex.Single.subscribe(Single.java:3575)
  at com.hivemq.client.internal.rx.RxFutureConverter$RxSingleFuture.<init>(RxFutureConverter.java:114)
  at com.hivemq.client.internal.rx.RxFutureConverter.toFuture(RxFutureConverter.java:44)
  at com.hivemq.client.internal.mqtt.MqttAsyncClient.publish(MqttAsyncClient.java:181)

I set the cleanStart to false, and left the other configs unchanged

**Comment by H0RIA** [comment]
Hi,

Just wanted to let you know that we managed to fix this. Silvio, you were right! Apparently, flooding the client with publish messages upon reconnect, does not go down well. What was happening is that during the network down time, we were accumulating in a separate queue some messages to be published (1 per minute). When the client would reconnect, all those accumulated messages were pushed to the broker... I think that this was happening before the client had the time to actually reconnect, so. Re-writing that queue of messages (and the way in which we push them to the broker) fixed the problem.

Thanks for your time!

**Comment by SgtSilvio** [comment]
Hi @H0RIA 
Glad to hear that you found a way forward.
And I agree that the behavior should be improved. We could either queue an infinite amount of messages while the client is disconnected or start failing publishes when the buffer reaches a certain size. The buffer should probably be configurable.
What do you think about this?

**Comment by H0RIA** [comment]
Hey Silvio,

Thanks again for the quick reply!
I guess that your suggestion about having this configurable is a good approach. It could be done either in terms of size (as byte size) or in terms of number of messages. The byte size approach seems better to me. Also, a default buffer size of a couple of KB should be more than fair...

One other possible "half-way" solution (less complicated than the previous) would be if there could be some sort of feedback from the hivemq client that something is not right. Sorry, but I did not look in detail at the hivemq client implementation to pin-point where that would go. However, if there would be a mechanism in which the client could say: "I am going to crash if you keep doing this" :), that would be great. Right now, the client just crashes. No valuable information can be retrieved from logcat. The only way to understand what happens is by looking on the device, in data/anr/traces.txt. With this notification about a problem in logcat, you don't need to implement a buffer management strategy and you give to the user enough information to do that in the application.

**Comment by SgtSilvio** [comment]
More control over offline message buffering will be addressed by #456 , so I will close this issue but link the information to #456
