### ISSUE TITLE
Async API never completes when subscribing to topic without permissions

### ISSUE THREAD

**Issue by siepkes** [hivemq/hivemq-mqtt-client#421]
I've ran in to the situation where I tried to subscribe to a topic for which the client had no permission using the async API and the `ComplableFuture` never completes. This was using HiveMQ 1.2.0.

The broker told the client it had insufficient permissions to subscribe. I checked with the broker in debug mode that the permission denied was actually send to the client. There also won't be any timeout, the HiveMQ client will just never complete the `ComplableFuture`.

## Expected behavior

When subscribing with the async API to a topic to which the client doesn't have access rights I expect the `CompletionStage` to complete exceptionally.

## Actual behavior

The `CompletionStage` will never complete. Not normally nor exceptionally.

## To Reproduce

On a topic to which the client has no rights:

```
mqttClient.subscribeWith()
	.topicFilter("topic/without/permissions")
	.callback(mqttPublish -> foo())
	.executor(callbackExecutorService)
	.send()
	.toCompletableFuture().get()
```

## Details
- Affected HiveMQ MQTT Client version(s): 1.2.0
- Used JVM version: OpenJDK 11.0.6 on FreeBSD 12.1

**Comment by SgtSilvio** [comment]
Hi @siepkes 
Thank you for your report.
This might be related to the automatic resubscribe feature introduced in version 1.2.0.
To verify this please answer the following questions: 
- Which MQTT version are you using?
- Which MQTT broker are you using?
- What is the action the broker performs when the authorization fails? Closing the connection, or sending a DISCONNECT to the client, or sending a SUBACK with an error code?
- Are you using automatic reconnect?
- Does the client disconnect and reconnect often?

**Comment by siepkes** [comment]
I was using MQTT 5 to connect to a VerneMQ 1.9.2 broker running on CentOS 7. 

The broker send an SUBACK with error code and left the connection open.

The client does not reconnect often (in the tests I ran it didn't need to reconnect at all). Automatic reconnect is enabled in the client as follows:

```java
KeyStore keyStore = loadKeystore(keyStoreLocation, keyStorePassphrase);
KeyManagerFactory kmf = createKeyManagerFactory(keyStore, keyStorePassphrase);

Mqtt5ClientBuilder clientBuilder = Mqtt5Client.builder()
	.sslWithDefaultConfig()
	.sslConfig(MqttClientSslConfig.builder()
			.keyManagerFactory(kmf)
			.build())
	.automaticReconnect(MqttClientAutoReconnect.builder()
			.initialDelay(500, TimeUnit.MILLISECONDS)
			.maxDelay(10, TimeUnit.SECONDS)
			.build())
	.identifier(clientId)
	.serverHost(brokerHost)
	.serverPort(brokerPort)
	.addDisconnectedListener(context -> {
		if(log.isTraceEnabled()) {
			log.trace("MQTT client disconnected.", context.getCause());
		} else {
			log.debug("MQTT client disconnected with error: '{}'.", context.getCause().getMessage());
		}
	})
	.addConnectedListener(context -> log.info ("MQTT client (re-)connected to broker '{}:{}'.", brokerHost, brokerPort));
```

Let me check if I can make a simple reproducer.

**Comment by SgtSilvio** [comment]
If reconnects are not involved here, it has nothing to do with automatic resubscribe.
A reproducer with Wireshark captures would really help.
Can you reproduce it every time?
Could be that the SUBACK packet from the server is malformed?

**Comment by siepkes** [comment]
I thought it would be a good idea to create a small reproducer with the new embedded HiveMQ broker but bumped into this issue: https://github.com/jitpack/jitpack.io/issues/4218. Hang in there, i'll workaround it.

**Comment by SgtSilvio** [comment]
@siepkes we do not need a completely self-contained reproducer. So if it is easier for you to reproduce it on your end, you could for example provide Wireshark captures that show the MQTT packet exchange.

**Comment by siepkes** [comment]
@SgtSilvio A Wireshark dump wasn't easy because the solution used TLS and my VerneMQ test broker also was configured for TLS only so I've tried to make a reproducer with the embeddable HiveMQ broker.

It's here: https://github.com/siepkes/hivemq-subscribe-test

The `hivemq-allow-all-extension` in it is actually a modified version **which blocks everything**. So don't be fooled by it :wink:. It's a hack to test connectivity because I'm bumping in to the exact same issue with connecting as with subscribing: When the client is not allowed to connect and the piece of code shown below is in the `connect` method (ie. not commented out) of the `HiveMqMqttClient` the connect future will never complete:

```lang=java
				.automaticReconnect(MqttClientAutoReconnect.builder()
						.initialDelay(500, TimeUnit.MILLISECONDS)
						.maxDelay(10, TimeUnit.SECONDS)
						.build())
```
Am I doing something wrong here?

**Comment by SgtSilvio** [comment]
> I'm bumping in to the exact same issue with connecting as with subscribing

When automatic reconnect is enabled, it will retry the initial connect until it finally succeeds. So this is not an issue and has nothing to do with the subscribe behavior you are seeing.
(FYI there is a ticket (#302 ) for adding configuration options for this)

> However you can't see the attempts because the listeners aren't called

The disconnected listener is called for every unsuccessful (re)connect attempt.

> what I noticed with subscriptions is that it blocks all other subscriptions. So a single subscription for which you get a permission denied acts as a poison pill for the rest of the application.

This is wrong. Concurrent subscribes are possible and they do not block each other. Maybe your application waits on 1 subscription before performing the next subscription.

We could not reproduce what you are seeing, so we would still be happy if you could provide more details about your application or even a reproducer.

**Comment by siepkes** [comment]
@SgtSilvio Your right, I'm starting to mix things up now. 

I need to take a step to get a clear picture of what is going on. Let me close this issue for now and I'll report back once I got all my ducks in a row again.
