### ISSUE TITLE
com.hivemq.client.mqtt.exceptions.ConnectionFailedException: java.net.UnknownHostException: Unable to resolve host "tcp://192.168.2.3": No address associated with hostname

### ISSUE THREAD

**Issue by StevenYan88** [hivemq/hivemq-mqtt-client#422]
HOST = "tcp://192.168.2.3"
Mqtt5Client.builder()
            .identifier(UUID.randomUUID().toString())
            .simpleAuth()
            .username("mqtt")
            .password("mqtt".toByteArray())
            .applySimpleAuth()
            .serverHost(HOST)
            .serverPort(1883)
            .automaticReconnect()
            .initialDelay(3, TimeUnit.SECONDS)
            .maxDelay(10, TimeUnit.SECONDS)
            .applyAutomaticReconnect()
            .addConnectedListener {
                Logger.d("mqtt连接上了")
            }.addDisconnectedListener {
                Logger.d("mqtt断开连接了"+it.cause)
            }
            .buildBlocking()
I cant connect server. the version is 1.1.4.
reason com.hivemq.client.mqtt.exceptions.ConnectionFailedException: java.net.UnknownHostException: Unable to resolve host "tcp://192.168.2.3": No address associated with hostname

**Comment by SgtSilvio** [comment]
Hi @StevenYan88 
serverHost refers to the host name or IP address of the MQTT broker.
HOST = "192.168.2.3" should work.

**Comment by StevenYan88** [comment]
The two devices are now connected via routers,It will then be connected via an Internet cable instead。We used org.eclipse.paho.client.mqttv3:1.2.0 before, like this client = new MqttClient(“tcp://192.168.2.3:1883”, username, null); But the performance is not good，Then we use this but connect error,We tried everything like you said ,Mqtt5Client.builder()
            .identifier(UUID.randomUUID().toString())
            .simpleAuth()
            .username("mqtt")
            .password("mqtt".toByteArray())
            .applySimpleAuth()
            .serverHost("192.168.2.3")
            .serverPort(1883)
            .automaticReconnect()
            .initialDelay(3, TimeUnit.SECONDS)
            .maxDelay(10, TimeUnit.SECONDS)
            .applyAutomaticReconnect()
but also not connected.

**Comment by SgtSilvio** [comment]
Please provide the connection error that you are now seeing.
Which MQTT broker are you using?

**Comment by StevenYan88** [comment]
mqtt5

**Comment by StevenYan88** [comment]
reason com.hivemq.client.mqtt.exceptions.ConnectionFailedException: java.net.UnknownHostException: Unable to resolve host "tcp://192.168.2.3": No address associated with hostname

**Comment by SgtSilvio** [comment]
Please remove the "tcp://" before the IP address

**Comment by StevenYan88** [comment]
I tried it and it still doesn't work

**Comment by SgtSilvio** [comment]
The exception indicates that you are still using the "tcp://" prefix.
Please provide the new error when you removed "tcp://".

**Comment by StevenYan88** [comment]
com.hivemq.client.mqtt.exceptions.ConnectionFailedException: java.net.UnknownHostException: Unable to resolve host "192.168.2.3": No address associated with hostname

**Comment by SgtSilvio** [comment]
Can you verify if the host is reachable?
Please also try version 1.2.0 of the hivemq-mqtt-client
