### ISSUE TITLE
How to use getResponseTopic with mqtt5AsyncClient

### ISSUE THREAD

**Issue by SameerTi** [hivemq/hivemq-mqtt-client#424]
Hi,
Closing it

**Comment by SgtSilvio** [comment]
Hi @SameerTi 
It is really hard to understand what your question is about.
Can you please describe an example step by step? Something like:
1. app -> iot device: sends message with topic 123
1. iot device -> app: ...

Maybe this blog post about the request/response pattern with MQTT 5 helps you: https://www.hivemq.com/blog/mqtt5-essentials-part9-request-response-pattern/

**Comment by SameerTi** [comment]
Hi @SgtSilvio 

Sure, here it is.

- app subscribe to **/app/mgr/#** with **Mqtt5AsyncClient**

- device1 (3.1 MQTT client using Mqtt3AsyncClient) PUBLISHES to topic **/app/mgr/reply-to=%2iot%2Fdevice**

- device2 (5.0 MQTT client using Mqtt5AsyncClient) PUBLISHES to topic **/app/mgr/** with responseTopic property set as  **/iot/device**

Apparently app, will get both messages, right ! because i'm using wild-card topic name i.e. /app/mgr/#
Now, app checks two properties upon getting message via callback 

1. getResponseTopic()  [In case of message from 5.0 device, this property gives **/iot/device**]
2. getTopic()                 [In case of message from 3.x device, this property gives **%2fiot%2fdevice**]

app would persist this response topic information and use to send a responses back to devices using Mqtt5AsyncClient 

so app using ONLY mqtt5AsyncClient however device(s) can use either 3.x or 5.x to connect to broker for message exchanges

Do you any issue with this approach, is the query..!? 
If yes, can you suggest anything else ?

**Comment by SameerTi** [comment]
Hi @SgtSilvio  any updates ?
