### ISSUE TITLE
SSL Handshake using .sslWithDefaultConfig() after update to 1.2.0 

### ISSUE THREAD

**Issue by virgiliomagalhaes** [hivemq/hivemq-mqtt-client#425]
## Expected behavior
Possibility to connect with broker using sslWithDefaultConfig() after update to hivemq 1.2.0

## Actual behavior
After update the hivemq client android for 1.2.0, when client try to connect with broker i received SSL Handshake no subject alt names.

## To Reproduce
```
private fun getMqttRxClientBuilder(): Mqtt3RxClient {
        val mqttClientBuilder = Mqtt3Client.builder()
            .serverHost(BuildConfig.MQTT_HOST)
            .serverPort(BuildConfig.MQTT_PORT)
            .identifier(MqttClientIdentifier.of(UUID.randomUUID().toString()))
            /*.automaticReconnect()
                .initialDelay(MQTT_INIT_DELAY, TimeUnit.MILLISECONDS)
                .maxDelay(MQTT_MAX_DELAY, TimeUnit.MILLISECONDS)
            .applyAutomaticReconnect()*/

        if (BuildConfig.USERNAME != "") {
            mqttClientBuilder.simpleAuth()
                .username(BuildConfig.USERNAME)
                .password(BuildConfig.PASSWORD.toByteArray())
                .applySimpleAuth()
        }

        if (BuildConfig.MQTT_PORT == MQTT_PORT_SSL) {
            mqttClientBuilder.sslConfig(getMqttSslConfigBuilder())
        } else {
            mqttClientBuilder.sslWithDefaultConfig()
        }

        return mqttClientBuilder.build().toRx()
    }

    private fun getMqttSslConfigBuilder(): MqttClientSslConfig {
        return MqttClientSslConfig.builder()
            .keyManagerFactory(context.getKeyManagerFactory(certificateAuthority, certificateKeyStore))
            .trustManagerFactory(context.getTrustManagerFactory(certificateAuthority, certificateKeyStore))
            .protocols(ImmutableList.of(PROTOCOL_TLS_V1, PROTOCOL_TLS_V1_1, PROTOCOL_TLS_V1_2))
            .build()
    }
```

### Steps
run the code above with hivemq client 1.4 and update to 1.2.0

## Details
- Affected HiveMQ MQTT Client version(s): 1.2.0
- Used JVM version: 1.8
- Used OS (name and version): Android Q
- Used MQTT version: MQTT 3
- Used MQTT broker (name and version): VERNEMQ

**Comment by SgtSilvio** [comment]
Hi @virgiliomagalhaes 
since 1.2.0 we have enabled hostname verification. It seems that your TLS certificate does not contain the host you are connecting to.
To verify if this is a problem with hostname verification, try disabling hostname verification:
```java
MqttClientSslConfig.builder()
        .hostnameVerifier((hostname, sslSession) -> true)
        ...
```
This is NOT recommended for production use. Please fix your certificates and host names.

**Comment by virgiliomagalhaes** [comment]
Hello @SgtSilvio thank you to support. Yes, i've imagined that problem can be this, but i don't know where i will change. Ok, thank you for your reply.
