### ISSUE TITLE
MQTT3: Manual acknowledgement for redelivered PUBLISH on CONN(clean-session=false)

### ISSUE THREAD

**Issue by yufei-cai** [hivemq/hivemq-mqtt-client#429]
Hi, I'm working on fault tolerance for a subscriber application using HiveMQ client against Mosquitto MQTT3 broker 1.6.2. The subscriber application uses manual acknowledgement to ensure proper processing of each incoming PUBLISH before they are acknowledged (QoS=1, 2). I can't convince HiveMQ client to exhibit the expected behavior described below. Am I missing something?

## Scenario

1. Subscriber application crashes. Some incoming QoS 1/2 PUBLISH messages are not acknowledged.
2. Subscriber application restarts. It sends CONN with `clean-session=false`.
3. Mosquitto broker replies CONNACK with `session-present=true`.
4. Mosquitto broker redelivers all unacknowledged PUBLISH messages sent to the subscriber application before the crash.

## Expected behavior

The subscriber application should process the redelivered PUBLISH messages and acknowledge them afterwards.

## Actual behavior

- HiveMQ client acknowledges the redelivered PUBLISH right away. Debugger lands on
  [MqttIncomingPublishService.java:96](https://github.com/hivemq/hivemq-mqtt-client/blob/c1b83c81cc5001b05962d85c6cbb44f9f65bd38c/src/main/java/com/hivemq/client/internal/mqtt/handler/publish/incoming/MqttIncomingPublishService.java#L96)

- Redelivered PUBLISH enter the global UNSOLICITED flow as Mqtt3Publish. The subscriber application can get hold of the redelivered PUBLISH by registering a callback for UNSOLICITED messages, but:
  - It cannot distinguish redelivered PUBLISH from actual unsolicited PUBLISH, since the DUP flag is not available in Mqtt3Publish;
  - It cannot prevent HiveMQ client from sending acknowledgements.
  - Calling `.acknowldge()` on the Mqtt3Publish inside the callback results in
    java.lang.UnsupportedOperationException: A publish must not be acknowledged if manual acknowledgement is not enabled.

### Steps

- Start Mosquitto broker with the configuration in the *Details* section.
- Run the reproducer
- Publish anything at any topic with QoS=1
- Kill the reproducer
- Run the reproducer again

### Reproducer code

```java
Mqtt3AsyncClient client;
// configure client to talk to the Mosquitto broker and use a FIXED client ID
client.publishes(MqttGlobalPublishFilter.UNSOLICITED, publish ->
        System.out.println("UNSOLICITED: " + publish)
        // To trigger UnsupportedOperationException:
        // publish.acknowledge();
);
client.connectWith().cleanSession(false).send().thenCompose(connAck -> {
    System.out.println(connAck);
    return client.subscribeWith()
            .topicFilter("#")
            .callback(publish -> {
                System.out.println(publish);
                // do not acknowledge on purpose to simulate crash during processing
            })
            .manualAcknowledgement(true)
            .send()
            .thenAccept(System.out::println);
});
```

## Details

- Affected HiveMQ MQTT Client version(s): 1.2.0

- Used JVM version: 11

- Used OS (name and version):

      # uname -a
      Linux archlinux 5.3.1-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 21 11:33:49 UTC 2019 x86_64 GNU/Linux

- Used MQTT version: 3.1.1

- Used MQTT broker (name and version): docker image eclipse-mosquitto:1.6.10 e19bf2a13315

      port 1883
      protocol mqtt
      log_type all

**Comment by SgtSilvio** [comment]
Hi @yufei-cai 

Version 1.2.0 decoupled subscription/publishing lifecycles from connection/session lifecycles.
This means you can subscribe before connecting and you do not need the workaround for the messages received between connect and subscribe.

> It cannot prevent HiveMQ client from sending acknowledgements.
Calling .acknowldge() on the Mqtt3Publish inside the callback results in
java.lang.UnsupportedOperationException: A publish must not be acknowledged if manual acknowledgement is not enabled.

Regarding manual acknowledgement: you have to enable it per stream/callback.
`subscribeWith()...manualAcknowledgement(true)...`
`subscribe(..., true)`
`publishes(..., true)`

**Comment by yufei-cai** [comment]
Subscribing before connecting fits my use case. Thanks a lot!
