### ISSUE TITLE
Where can i download the pre-compiled .jar file for hivemq-mqtt-client?

### ISSUE THREAD

**Issue by martijintro** [hivemq/hivemq-mqtt-client#435]
Hi there

Where can i download the pre-compiled .jar file for hivemq-mqtt-client?

Thank you for your feedbacks.

With kind regards,
Jan

**Comment by SgtSilvio** [comment]
Hi @martijintro 
The HiveMQ MQTT Client is available as Maven dependency via Maven Central.
Look at the documentation how to include it in your project: https://hivemq.github.io/hivemq-mqtt-client/docs/installation/
If you want to only download the jar, you can do it via Maven Central: https://mvnrepository.com/artifact/com.hivemq/hivemq-mqtt-client
We highly recommend using a build tool.

**Comment by jayjupdhig** [comment]
Ok thx.
