### ISSUE TITLE
How to use a tls connection?

### ISSUE THREAD

**Issue by Tockra** [hivemq/hivemq-mqtt-client#440]
Hi Guys,

I didn't find a tutorial how to use a TLS Connection with your java client.
Clients of other programming languages can get a ca.crt as trust store. 

What is the equivalent for your client?
I saw following:
https://github.com/hivemq/hivemq-mqtt-client/issues/324

But I get no one of these solutions to run. 

Why is it necessary to give the client the servers pub-key, private-key and CA ? 

My mqtt broker has a public key (server.crt) a private key (server.key) and a self signed ca (ca.crt).
The go and rust paho clients just need the ca.crt to verify the server.crt...

T

**Comment by Tockra** [comment]
Found a solution:
```java
private void setupSslConfig(Mqtt5ClientBuilder clientBuilder, String caPath) throws NoSuchAlgorithmException, KeyStoreException, CertificateException, IOException {
        MqttClientSslConfigBuilder.Nested<? extends Mqtt5ClientBuilder> sslConfig = clientBuilder.sslConfig();

        sslConfig.trustManagerFactory(getTrustManagerFactory(caPath));
        sslConfig.applySslConfig();
    }

    private TrustManagerFactory getTrustManagerFactory(String caPath) throws CertificateException, NoSuchAlgorithmException, IOException, KeyStoreException {
        Security.addProvider(new BouncyCastleProvider());

        X509Certificate caCert = getCertificate(caPath);  //<- hier dein pfad zum ca.crt eintragen

        /**
         * CA certificate is used to authenticate server
         */
        KeyStore caKeyStore = KeyStore.getInstance(KeyStore.getDefaultType());
        caKeyStore.load(null, null);
        caKeyStore.setCertificateEntry("ca-certificate", caCert);

        TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(
                TrustManagerFactory.getDefaultAlgorithm());
        trustManagerFactory.init(caKeyStore);
        return trustManagerFactory;
    }

    private X509Certificate getCertificate(String path) {
        try (PEMParser reader = new PEMParser(Files.newBufferedReader(Paths.get(path)))) {

            X509CertificateHolder caCertHolder = (X509CertificateHolder) reader.readObject();
            return new JcaX509CertificateConverter().setProvider("BC").getCertificate(caCertHolder);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
```

**Comment by liangyuanpeng** [comment]
> Found a solution:
> 
> ```java
> private void setupSslConfig(Mqtt5ClientBuilder clientBuilder, String caPath) throws NoSuchAlgorithmException, KeyStoreException, CertificateException, IOException {
>         MqttClientSslConfigBuilder.Nested<? extends Mqtt5ClientBuilder> sslConfig = clientBuilder.sslConfig();
> 
>         sslConfig.trustManagerFactory(getTrustManagerFactory(caPath));
>         sslConfig.applySslConfig();
>     }
> 
>     private TrustManagerFactory getTrustManagerFactory(String caPath) throws CertificateException, NoSuchAlgorithmException, IOException, KeyStoreException {
>         Security.addProvider(new BouncyCastleProvider());
> 
>         X509Certificate caCert = getCertificate(caPath);  
> 
>         /**
>          * CA certificate is used to authenticate server
>          */
>         KeyStore caKeyStore = KeyStore.getInstance(KeyStore.getDefaultType());
>         caKeyStore.load(null, null);
>         caKeyStore.setCertificateEntry("ca-certificate", caCert);
> 
>         TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(
>                 TrustManagerFactory.getDefaultAlgorithm());
>         trustManagerFactory.init(caKeyStore);
>         return trustManagerFactory;
>     }
> 
>     private X509Certificate getCertificate(String path) {
>         try (PEMParser reader = new PEMParser(Files.newBufferedReader(Paths.get(path)))) {
> 
>             X509CertificateHolder caCertHolder = (X509CertificateHolder) reader.readObject();
>             return new JcaX509CertificateConverter().setProvider("BC").getCertificate(caCertHolder);
>         } catch (Exception e) {
>             e.printStackTrace();
>         }
>         return null;
>     }
> ```

It's working for me, thanks .
