### ISSUE TITLE
Disable redelivery of published and inflight messages

### ISSUE THREAD

**Issue by patrickjuchli** [hivemq/hivemq-mqtt-client#442]
I've seen that you're currently working on message persistence and checkpointing #305 which might answer this issue in another way soon.

Until then, or just generally, I need to do the following: 

An MQTT client instance should reconnect automatically using `automaticReconnect()`. If it reconnects, it must not try to redeliver previous inflight messages. I want to have full control over redelivery attempts because I'm using a custom persistence solution with payloads to be sent. I'd like to use the MQTT client as conservatively as possible: Publish a payload with QoS 1. If that worked successfully (ack reveived), remove the entries from my buffer, and continue publishing the next payload.

I'm aware that this might not be how an MQTT client should work ideally. Ideally these things should be reliably taken care of. To be frank – that's not always the case.

Is something like I've described above possible with 1.2.x?

**Comment by SgtSilvio** [comment]
Hi @patrickjuchli 
Are you using the client to publish and receive messages?
If you only publish messages then you can just use a session expiry interval of 0. Then all inflight and queued messages are failed when the connection is lost and you can retry them manually when the client is reconnected.
Does this help you?

Kind regards
Silvio

**Comment by patrickjuchli** [comment]
That could help, thanks. How do I set the session expiry interval? I can't seem to find anything by that name.

**Comment by SgtSilvio** [comment]
Actually the session expiry interval is by default 0, so you do not need to set it but you can to be explicit.

For MQTT 5: `client.connectWith.sessionExpiryInterval(0).send();`
Documentation: https://hivemq.github.io/hivemq-mqtt-client/docs/mqtt-operations/connect/#session-expiry-interval

For MQTT 3: `client.connectWith.cleanSession(true).send();`

**Comment by patrickjuchli** [comment]
Thanks!

And if I use `mqtt.publishWith() ... send()` with an async client, the returned future is resolved when the MQTT Puback from the broker has been received or already before when the client managed to just send the Publish packet?

**Comment by SgtSilvio** [comment]
> And if I use `mqtt.publishWith() ... send()` with an async client, the returned future is resolved when the MQTT Puback from the broker has been received

Yes, correct. With MQTT 5 you even get the Mqtt5PubAck as part of the Mqtt5PublishResult.

**Comment by patrickjuchli** [comment]
Great, thanks a lot for your help.
