### ISSUE TITLE
Hundreds of Proguard Warnings when building APK

### ISSUE THREAD

**Issue by aloz77** [hivemq/hivemq-mqtt-client#443]
## Expected behavior
No warnings when prod build the app in Android Studio 4.0.1

## Actual behavior
Get 414 Proguard warnings and build is stopped

```
:app:minifyFullyStdReleaseWithProguard
io.netty.handler.codec.marshalling.ChannelBufferByteInput: can't find superclass or interface org.jboss.marshalling.ByteInput
io.netty.handler.codec.marshalling.ChannelBufferByteOutput: can't find superclass or interface org.jboss.marshalling.ByteOutput
io.netty.handler.codec.marshalling.LimitingByteInput: can't find superclass or interface org.jboss.marshalling.ByteInput
io.netty.handler.ssl.ConscryptAlpnSslEngine$BufferAdapter: can't find superclass or interface org.conscrypt.AllocatedBuffer
io.netty.handler.ssl.ConscryptAlpnSslEngine$BufferAllocatorAdapter: can't find superclass or interface org.conscrypt.BufferAllocator
io.netty.handler.ssl.ConscryptAlpnSslEngine$ClientEngine$1: can't find superclass or interface org.conscrypt.HandshakeListener
...
...
...
Please correct the above warnings first
```

### Steps

Start APK Build in Android Studio

### Reproducer code

proguard-rules.pro

```
-keepclassmembernames class io.netty.** { *; }
-keepclassmembers class org.jctools.** { *; }

```

build.gradle

```
    packagingOptions {
        exclude 'META-INF/INDEX.LIST'
        exclude 'META-INF/io.netty.versions.properties'
    }

    implementation group: 'com.hivemq', name: 'hivemq-mqtt-client', version: '1.2.1'
    implementation 'net.sourceforge.streamsupport:android-retrostreams:1.7.2'
    implementation 'net.sourceforge.streamsupport:android-retrofuture:1.7.2'
```

gradle.properties

```
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configureondemand=true
android.enableBuildCache=true

android.enableR8 = false
android.useAndroidX=true
android.enableJetifier=true
```

Can suppress warnings by adding to proguard-rules.pro. Is it safe?

```
-dontwarn io.netty.**
-dontwarn sun.security.**
-dontwarn org.bouncycastle.**
-dontwarn org.eclipse.**
-dontwarn com.google.protobuf.**
-dontwarn com.jcraft.jzlib.**
-dontwarn org.jboss.marshalling.**
-dontwarn org.slf4j.**
-dontwarn sun.misc.**

```

## Details
- Affected HiveMQ MQTT Client version(s): 1.2.1
- Gradle version: 6.3
- Android Studio Version: 4.0.1

**Comment by SgtSilvio** [comment]
Hi @aloz77 
> android.enableR8 = false

You are using plain proguard and not the one of the android build tool.
Is it important for you to use disable R8? If not, please try with R8.
If you need to use plain proguard, you need to add these `dontwarn` rules.

It would be great if you could find out the minimum required proguard rules so that we can add them to the documentation.

**Comment by aloz77** [comment]
Building with R8 is working without warnings.

I use proguard as this feature is unfortunately not supported by R8:

`-keepattributes SourceFile,LineNumberTable`

If dontwarn rules as above are safe I prefer to live with them.

**Comment by SgtSilvio** [comment]
@aloz77 Sorry for the long delay.
The dontwarn rules are safe as netty has a lot of optional functionality with optional dependencies that proguard does not find. The code that refers to these optional dependencies is never executed so you can safely ignore them.
I will close this issue now.
Feel free to comment here or open another issue if you find any problems.
