### ISSUE TITLE
Exception without stacktrace

### ISSUE THREAD

**Issue by degill** [hivemq/hivemq-mqtt-client#444]
## Problem
Hello there,

currently in one of my apps I have the following issue:

When I disconnect my client, somewhere the following exception is thrown. But since I get no stacktrace or anything I don't know how I can handle it and my app crashes. The only info I see in my logcat are the following two statements.

```
09-30 16:01:13.712  8476  8693 E AndroidRuntime: com.hivemq.client.mqtt.exceptions.MqttSessionExpiredException: Session expired as connection was closed.
09-30 16:01:13.712  8476  8693 E AndroidRuntime: Caused by: com.hivemq.client.mqtt.mqtt3.exceptions.Mqtt3DisconnectException: Client sent DISCONNECT
```

Any help here would be appreciated on how I can narrow down to find the offending code on my side.

**Comment by SgtSilvio** [comment]
Hi @degill 
Sorry for the delayed response.
I guess you are using the `Mqtt3RxClient` API. Please give more information about your code and the version of the library you are using. Sharing some code snippets would also help.
This exception is delivered to `Flowable`s that are returned by `subscribePublishes` (or `subscribeStream` (deprecated)) or `publishes` via `onError` to notify you that the session and therefore also the subscription ended.

**Comment by degill** [comment]
Hey @SgtSilvio 
Sorry for the really late response, it's for a project I am not working on constantly enough 😅 

No, we are not using `Mqtt3RxClient` but the `Mqtt3BlockingClient`. It seems that the exception is thrown (at least in our codebase) at two places:

1. when calling `Mqtt3BlockingClient.Mqtt3Publishes.receive(Long, TimeUnit)`
2. when calling `Mqtt3PublishBuilder.SendVoid.send()`

We worked around it by catching the offending excepions at those places. Still I am curious on why there is no stacktrace at this point 🤔

**Comment by SgtSilvio** [comment]
With the blocking API you should always get stack traces. I will close this issue now, but if you still see missing stack traces with the blocking API, please create a new ticket.
