### ISSUE TITLE
reauthenticating if token is expired(reconnecting with new token)

### ISSUE THREAD

**Issue by MrSatan** [hivemq/hivemq-mqtt-client#450]
## Problem or use case
hello there . i create my client and connect to server when app is initiated . i use simple auth -> password is my token across the app. when my token is expired , i get disconnect event with error of not authorized . it is ok . but when i reAuth using rest and receiving new token , i can't apply the new token to my connection . because it is always tring to reconnect with prev token . 

## Preferred solution or suggestions
any method to shoutdown the client or stop it from reconnecting or applying new auth ? 
i know there is client.disconnect ,  but im handling the notAuthorized in ondisconnect event , when i disconnect it there , app will enter endless loop .
i use mqtt3

**Comment by SgtSilvio** [comment]
Hi @MrSatan 
You can set new authentication data via the DisconnectedListener.
```java
    ...
    .addDisconnectedListener(context -> {
        TypeSwitch.when(context).is(Mqtt3DisconnectedContext.class, mqtt3Context -> {
            mqtt3Context.getReconnector().connectWith()
                    .simpleAuthWith()
                        .username("test")
                        .password("changeme".getBytes())
                        .applySimpleAuth()
                    .applyConnect();
        });
    });
```

**Comment by SgtSilvio** [comment]
You could also use the `reconnectWhen` method, for example:
```java
    .addDisconnectedListener(context -> {
        TypeSwitch.when(context).is(Mqtt3DisconnectedContext.class, mqtt3Context -> {
            mqtt3Context.getReconnector().reconnectWhen(callAuthService(), (authResult, error) -> {
                mqtt3Context.getReconnector().connectWith()
                        .simpleAuthWith()
                            .username("test")
                            .password(authResult.getToken())
                            .applySimpleAuth()
                        .applyConnect();
            });
        });
    });
```

**Comment by SgtSilvio** [comment]
I will close this ticket now, but please do not hesitate to comment or open a new issue.
