### ISSUE TITLE
After manual reconnection disconnected message gets printed after successful connection

### ISSUE THREAD

**Issue by Zeroneca** [hivemq/hivemq-mqtt-client#451]
## Expected behavior

After rebuilding the client, disconnecting and reconnecting, connection is established and works.

## Actual behavior

Connection is established, a new exception gets fired and a disconnected message appears, even if the client is connected.

### Steps

Disconnect client, rebuild client with new configuration and connect. See example in file below (with workaround of reconnecters which don't get closed on disconnection).

### Reproducer code

[App.txt](https://github.com/hivemq/hivemq-mqtt-client/files/5666991/App.txt)

## Details
- Affected HiveMQ MQTT Client version(s): 1.2.1
- Used JVM version: 1.8.0_272
- Used OS (name and version): Gentoo Linux
- Used MQTT version: 3
- Used MQTT broker (name and version): Mosquitto (test.mosquitto.org)

**Comment by Zeroneca** [comment]
I just successfully wrote a workaround for that problem.

After the manual disconnect the previous connection exception needs some time to fire.
Now I just renewed the ClientIdentifier on reconnection, saved the current client identifier in the connect method and only printed the error message, when the current client has the same identifier as the identifier previous saved, when the connect method was called.

The new connect method looks like this:

```java
    private void connectClient() {
        client = clientBuilder.buildAsync();
        String uuid = client.getConfig().getClientIdentifier().toString();
        client.connect().whenComplete((ack, e) -> {
            if (e != null && uuid.equals(client.getConfig().getClientIdentifier().toString())) {
                System.out.println("Couldn't connect!");
            } else {
                System.out.println("Connected!");
            }
        });
    }
```

Another think I recognized too, is that it seems it's not possible to catch exceptions related to SSL certificates. Did I miss something or is this actually not possible? Could be better placed in a new issue I guess.

**Comment by SgtSilvio** [comment]
Hi @Zeroneca 
sorry that we did not answer here yet, your issue must have slipped through.
If I understood it correctly, then you have issues with cancelling the reconnect if the initial connect fails. For that there is already an issue: https://github.com/hivemq/hivemq-mqtt-client/issues/306, so I will close this issue as a duplicate.

> Another thing I recognized too, is that it seems it's not possible to catch exceptions related to SSL certificates.
SSL exceptions are wrapped in a ConnectionFailedException and can be handled via the connect method (the blocking API throws the ConnectionFailedException, the async API completes the CompletableFuture with the exception, the reactive API delivers the exception via the onError callback).
