### ISSUE TITLE
Retain not work on clearsession false

### ISSUE THREAD

**Issue by MrSatan** [hivemq/hivemq-mqtt-client#452]
## Expected behavior
when i subscribe once to a topic and clear session is false , the next time i open the app , session is present but retain values are not received . i should subscribe again to topic to receive the retain value . 
latest version
tested on android

**Comment by SgtSilvio** [comment]
Hi @MrSatan 
Retained messages are only delivered after subscribing.
If you reconnect and still have a session present, then the broker should have queued all messages for the period your client was offline. For these "normal" queued messages the retain flag will be false.

I will close this issue now as what you describe is correct according to the MQTT specification.
Please do not hesitate to comment or open a new issue if I misunderstood something.
