### ISSUE TITLE
How to avoid subscribing to the same topic and fire the callback multiple times?

### ISSUE THREAD

**Issue by denebchorny** [hivemq/hivemq-mqtt-client#454]
## Expected behavior
I want to have a callback to listen to every topic I subscribe to just once per message sent. I mean, I want to subscribe to a topic 1000 times, but when a message is received, I want to listen to it just one time.

IDK if there is something I am doing wrong (I guess).

## Actual behavior
- I am developing a home security camera app. 
- I have a list of cameras that I own. 
- For every camera on the list, I subscribe to a topic.
- Every 30s, I update the screen, and again I subscribe to a topic for every camera. This means a TOPIC could be subscribed many times.
- Every time I receive a message on a topic, the callback fires messages about how many times the same topi was subscribed.

### Steps

1. haven a topic **camera/123**
2. subscribe the topic N times with the below method called **subscribeWith**
3. Send a message over **camera/123**
4. You will receive the message N times because the N time you subscribed to the topic

### Reproducer code
**Just variables**
```
private var mqtt: Mqtt5AsyncClient? = null
private var username: String? = null
private var password: String? = null
private val serverHost: String,
private val serverPort: Int = 1883
```

**Build the MQTT**
```
private fun build() {
        if (mqtt != null) return

        mqtt = Mqtt5Client.builder()
                .identifier(identifier())
                .serverHost(serverHost)
                .serverPort(serverPort)
                .automaticReconnect()
                .applyAutomaticReconnect()
                .addConnectedListener { Timber.d("On Connected") }
                .addDisconnectedListener { onMQTTDisconnected(it) }
                .buildAsync()
    }
```

**Connecting the MQTT**
```
fun connect(username: String, password: String) {
        build()

        this.username = username
        this.password = password

        mqtt?.connectWith()
                ?.keepAlive(30)
                ?.sessionExpiryInterval(7200)
                ?.cleanStart(false)
                ?.simpleAuth()
                ?.username("abc")
                ?.password("123".toByteArray())
                ?.applySimpleAuth()
                ?.send()
    }
```

**And then, subscribing a topic**
Every time I subscribe a topic I use these fun
```
fun subscribeWith(topic: String) {
        mqtt?.subscribeWith()
                ?.topicFilter(topic)
                ?.qos(MqttQos.AT_MOST_ONCE)
               ?.callback { t -> onConsumingTopic(t) }  <- I THINK THIS IS THE IMPORTANT THING
                ?.send()
                ?.whenComplete { ack, error -> onTopicConnected(ack, error, topic) }

    }
```

## Details
OS: Android 7, 8 and 10
Broker: EMQX
Extra: This behavior doesn't happen with  an iOS

**Comment by SgtSilvio** [comment]
Hi @denebchorny 
You do not need to register a callback for every subscribe call.
Instead you could register one "global" callback for all messages, for example:
```java
client.publishes(MqttGlobalPublishFilter.SUBSCRIBED, publish -> { ... } );
```
and then you can subscribe without providing a callback.
```java
client.subscribeWith().topicFilter("test").qos(MqttQos.AT_LEAST_ONCE).send();
```

**Comment by SgtSilvio** [comment]
I will close this issue now, as I hope this answers your question.
Please do not hesitate to comment or open a new issue.

**Comment by frankyfish** [comment]
Hello @SgtSilvio. Just hit the same problem which resulted in data duplication (several same callbacks have been executed whenever my app received something via MQTT). This took quite a time to investigate. Solution with single callback registration helped.
Could you please add a notice/warning in the javadoc may be? 
To me this seems like not that obvious thing especially for someone coming with paho-mqtt background.

Btw the problem doesn't seem to occur if the HiveMQ broker itself is restarted. The same piece of code that lead to additional callback registration and data duplication(when mqtt-subscriber was disconnected via web-ui) worked fine whenever HiveMQ has been restarted and connection re-established. In fact for some time restart of the HiveMQ has been fixing data duplication for me. This blows my mind a bit.
