### ISSUE TITLE
mqtt3.1

### ISSUE THREAD

**Issue by Sunnoc** [hivemq/hivemq-mqtt-client#458]
Will you consider supporting mqtt3.1 in the future? Some servers still use version 3.1

**Comment by dobermai** [comment]
Hi Sunnoc,

currently we don’t have any plans supporting MQTT 3.1. Most brokers nowadays support 3.1.1 and 5. Is there any broker in particular you’d like to see 3.1 support for?

**Comment by Sunnoc** [comment]
> 嗨，Sunnoc，
> 
> 当前，我们还没有任何计划支持MQTT 3.1。如今，大多数经纪人都支持3.1.1和5。您是否特别想获得3.1经纪人的支持？

Yes, I want to use 3.1
