### ISSUE TITLE
Variant resolution failure since gradle 6

### ISSUE THREAD

**Issue by mathieuruellan** [hivemq/hivemq-mqtt-client#459]
Build failure after moving from gradle 5.4 to gradle 6.6.1

My dependency is:

> implementation group: 'com.hivemq', name: 'hivemq-mqtt-client-websocket', version: '1.2.1'

(No error if i set a platform dependency, but, i don't get transitive dependencies.)

The error:

> > Could not resolve com.hivemq:hivemq-mqtt-client-websocket:1.2.1.
>      Required by:
>          project :myscript-cloud-iink-nebo-services
>       > No matching variant of com.hivemq:hivemq-mqtt-client-websocket:1.2.1 was found. The consumer was configured to find an API of a library compatible with Java 11, preferably in the form of class files, and its dependencies declared externally but:
>           - Variant 'apiElements' capability com.hivemq:hivemq-mqtt-client-websocket:1.2.1 declares an API of a component:
>               - Incompatible because this component declares a platform and the consumer needed a library
>               - Other compatible attributes:
>                   - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
>                   - Doesn't say anything about its target Java version (required compatibility with Java 11)
>                   - Doesn't say anything about its elements (required them preferably in the form of class files)
>           - Variant 'enforcedApiElements' capability com.hivemq:hivemq-mqtt-client-websocket-derived-enforced-platform:1.2.1 declares an API of a component:
>               - Incompatible because this component declares an enforced platform and the consumer needed a library
>               - Other compatible attributes:
>                   - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
>                   - Doesn't say anything about its target Java version (required compatibility with Java 11)
>                   - Doesn't say anything about its elements (required them preferably in the form of class files)
>           - Variant 'enforcedRuntimeElements' capability com.hivemq:hivemq-mqtt-client-websocket-derived-enforced-platform:1.2.1 declares a runtime of a component:
>               - Incompatible because this component declares an enforced platform and the consumer needed a library
>               - Other compatible attributes:
>                   - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
>                   - Doesn't say anything about its target Java version (required compatibility with Java 11)
>                   - Doesn't say anything about its elements (required them preferably in the form of class files)
>           - Variant 'runtimeElements' capability com.hivemq:hivemq-mqtt-client-websocket:1.2.1 declares a runtime of a component:
>               - Incompatible because this component declares a platform and the consumer needed a library
>               - Other compatible attributes:
>                   - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
>                   - Doesn't say anything about its target Java version (required compatibility with Java 11)
>                   - Doesn't say anything about its elements (required them preferably in the form of class files)
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings
> 
> 

>

**Comment by SgtSilvio** [comment]
Hi @mathieuruellan 
This happens because the newer gradle version automatically uses gradle module metadata instead of the maven pom.
The following works:
```groovy
    implementation("com.hivemq:hivemq-mqtt-client:1.2.1")
    implementation(platform("com.hivemq:hivemq-mqtt-client-websocket:1.2.1"))
```

> (No error if i set a platform dependency, but, i don't get transitive dependencies.)

You get the transitive websocket dependencies on the runtimeClassPath.

The same works also for the `proxy` and `epoll` modules.

Sorry for the inconvenience. We will fix this in the next version.
If there are any further questions please comment.

**Comment by milbrandt** [comment]
Would be good to have at least a hint in the documentation as temporary workaround.

**Comment by SgtSilvio** [comment]
Sorry for the inconvenience. Now there is a hint in the documentation and in the readme.

**Comment by pglombardo** [comment]
Hi all - This has been fixed in the latest versions.  If anything remains, please feel free to open another issue.  We'd be happy to help out!
