### ISSUE TITLE
Both, async and sync clients blocks forever when subscribing in connect handler

### ISSUE THREAD

**Issue by micw** [hivemq/hivemq-mqtt-client#460]
I create the following client:

```
		Mqtt3ClientBuilder builder=Mqtt3Client.builder()
				.identifier(mqttClientId)
				.serverHost(mqttHost)
				.serverPort(mqttPort)
				.automaticReconnectWithDefaultConfig()
				.addConnectedListener((context)->subscribeMqtt())
		        .addDisconnectedListener(context -> {
		        	System.err.println(context.getClientConfig().getState());
		        	log.warn("Lost MQTT connection to {}:{} with client id {}",mqttHost,mqttPort,mqttClientId);
		        	// Workaround for https://github.com/hivemq/hivemq-mqtt-client/issues/302 - for test use invalid credentials
		            if (context.getClientConfig().getState() == MqttClientState.CONNECTING) {
		                context.getReconnector().reconnect(false);
		            }
		        })
				.transportConfig()
				    .mqttConnectTimeout(10, TimeUnit.SECONDS)
				    .socketConnectTimeout(10, TimeUnit.SECONDS)
				    .applyTransportConfig()
				;
```

In subscribeMqtt I subscribe and wait for the future to complete:

```
				try {
					mqttClient.subscribeWith()
						.topicFilter(topic)
						.qos(MqttQos.AT_LEAST_ONCE)
						.send().get();
					log.debug("Subscribed to topic {}",topic);
				} catch (Exception ex) {
					log.warn("Unable to subscribe to {}",topic,ex);
				}

```

## Expected behavior

The client should subscribe on each connection

## Actual behavior

The subscribe code blocks forever

### Reproducer code

See code above.

## Details
- Affected HiveMQ MQTT Client version(s): 1.2.1
- Used JVM version: openjdk-11
- Used OS (name and version): linux (archlinux)
- Used MQTT version: 3
- Used MQTT broker (name and version): vernemq 1.11.0

**Comment by micw** [comment]
In addition, I cannot normally stop the java process in this case (using "stop" Button in eclipse - I need to kill the JVM).

**Comment by micw** [comment]
According to https://github.com/hivemq/hivemq-mqtt-client/issues/325 it should at least work with the async client.

**Comment by SgtSilvio** [comment]
Hi @micw 
You block inside the ConnectedListener, which is not allowed

see javadoc: https://javadoc.io/doc/com.hivemq/hivemq-mqtt-client/latest/index.html
> Listener method which is notified when a client is connected (a successful ConnAck message is received).
This method must not block.

You have to remove the blocking `.get()` call.
You can instead add a listener, for example:
```java
mqttClient.subscribeWith()
        .topicFilter(topic)
        .qos(MqttQos.AT_LEAST_ONCE)
        .send()
        .whenComplete((subAck, error) -> {
            if (error == null) {
                log.debug("Subscribed to topic {}", topic);
            } else {
                log.warn("Unable to subscribe to {}", topic, error);
            }
        });
```

**Comment by SgtSilvio** [comment]
I will close this issue now.
Please do not hesitate to comment if something is still unclear.
