### ISSUE TITLE
CONNECT failed as CONNACK contained an Error Code: NOT_AUTHORIZED

### ISSUE THREAD

**Issue by StevenYan88** [hivemq/hivemq-mqtt-client#463]
com.hivemq.client.mqtt.mqtt5.exceptions.Mqtt5ConnAckException: CONNECT failed as CONNACK contained an Error Code: NOT_AUTHORIZED

## Details
- Affected HiveMQ MQTT Client version(s): 
- Used JVM version: 
- Used OS (name and version): 
- Used MQTT version: 1.2.1
- Used MQTT broker (name and version):

**Comment by SgtSilvio** [comment]
Hi @StevenYan88 
It is not clear what your issue is about.

> CONNECT failed as CONNACK contained an Error Code: NOT_AUTHORIZED

This message tells you that you are not authorized to connect to your MQTT broker.
The cause may be missing or wrong authentication data like username and password.
