### ISSUE TITLE
Support For RxJava3

### ISSUE THREAD

**Issue by Brabalawuka** [hivemq/hivemq-mqtt-client#465]
## Feature Request: Any plan to support RxJava3?

Since RxJava 2 will terminate their support in Feb 2021, do we have any plan switching to RxJava3?

https://github.com/ReactiveX/RxJava

**Comment by SgtSilvio** [comment]
Hi @Brabalawuka 
yes, we are already aware of this.
Version 2 of the HiveMQ MQTT Client will use RxJava3. There already exists a develop-2 branch (https://github.com/hivemq/hivemq-mqtt-client/tree/develop-2) but it is not release-ready yet.

**Comment by Blafasel3** [comment]
Any updates on this?
