### ISSUE TITLE
Broken links in docu at https://hivemq.github.io/hivemq-mqtt-client/docs/

### ISSUE THREAD

**Issue by milbrandt** [hivemq/hivemq-mqtt-client#469]
## Expected behavior

All links lead to content and not to "Page not found"

## Actual behavior

Seems like all the pages referencing to a markdown are broken

### Steps

On [Client Configuration](https://hivemq.github.io/hivemq-mqtt-client/docs/client-configuration/) follow
- [Thread Management](https://hivemq.github.io/hivemq-mqtt-client/docs/client-configuration/thread-management.md)
- [Security](https://hivemq.github.io/hivemq-mqtt-client/docs/client-configuration/security/ssl-tls.md)
- [Transport](https://hivemq.github.io/hivemq-mqtt-client/docs/client-configuration/transports/websocket.md)

On Connect
- [Enhanced auth](https://hivemq.github.io/hivemq-mqtt-client/docs/mqtt-operations/security/auth.md)

**Comment by SgtSilvio** [comment]
Hi @milbrandt 
Thank you for your report.
The documentation of the hivemq-mqtt-client is not yet complete unfortunately.
If you have a question about a specific topic, please feel free to ask here or on our community forum (https://community.hivemq.com/).
