### ISSUE TITLE
Spring Boot Starter

### ISSUE THREAD

**Issue by deen13** [hivemq/hivemq-mqtt-client#471]
Hey HiveMQ Team, 

we at @smartsquarehq are currently working on a spring boot mqtt starter using your client under the hood. We would really appreciate it if you could list our starter so that we can get more feedback. :) 

https://github.com/SmartsquareGmbH/mqtt-starter

**Comment by MicWalter** [comment]
Hi @deen13,

you can check PR #472 to see if this is okay for you. 

I took the liberty to use your GitHub avatar image, do you want another logo instead?

Greetings
Michael from the HiveMQ team

**Comment by deen13** [comment]
Great! Thank you!!! :)

**Comment by MicWalter** [comment]
Closing this issue as PR is merged
