### ISSUE TITLE
When connect to a new wifi in Android, Mqtt does not work well

### ISSUE THREAD

**Issue by acaliaro** [hivemq/hivemq-mqtt-client#477]
We are using the HiveMQ client in our MDM agent. We noticed that when the agent creates a new wifi network and connects to it, the HiveMQ client stops receiving and sending messages, despite its status being CONNECTED. It seems that it does not automatically recognize the switch to the first to the second wifi. As a workaround, when the agent receives the Network Disconnected broadcast, it closes the mqtt, and reopens it when it receives the next Network Connected.
Is it correct that the mqtt is unable to automatically switch from one wifi network to another?
Thank you

**Comment by SgtSilvio** [comment]
Hi @acaliaro 
MQTT detects broken connections by the keep alive mechanism. Which keep alive interval are you using?

**Comment by SgtSilvio** [comment]
I will close this issue due to inactivity and in general reconnecting on a different network should work.
Please feel free to comment and reopen if you have additional information.
