### ISSUE TITLE
How to Handle Timeouts While Publishing a Message

### ISSUE THREAD

**Issue by teivah** [hivemq/hivemq-mqtt-client#485]
## Expected behavior

I didn't know how to report it but I can't find in the documentation how to set up a timeout while publishing a message.
[Here](https://github.com/hivemq/hivemq-mqtt-client#consume-messages), it's described while consuming messages but what about publishing?

So far, I've been using the `Mqtt5BlockingClient`:

```java
client = builder.buildBlocking();
client.connect();

client.toAsync()
		.subscribeWith()
		.topicFilter(topic)
		.qos(qos)
		.callback(consumer)
		.send()
		.get();

// ...

client.publishWith()
		.topic(messageTopic)
		.payload(payload)
		.qos(messageQOS)
		.messageExpiryInterval(messageExpirySeconds)
		.send();
```

In this process, how can I attach a timeout, please?

## Details
- Affected HiveMQ MQTT Client version(s): 
- Used JVM version: 
- Used OS (name and version): 
- Used MQTT version: 
- Used MQTT broker (name and version):

**Comment by SgtSilvio** [comment]
Sorry for the delay, I will still answer here in the next few days, but unfortunately did not find the time in the last weeks.

**Comment by teivah** [comment]
Hey @SgtSilvio, thanks for your answer. Any news, please.

**Comment by mat0pad** [comment]
@teivah @SgtSilvio Did you figure out a method to specify a publish timeout? We are facing similar issue.

**Comment by outsideMyBox** [comment]
I have the same question for MQTT3. I can't find anywhere how to set it.
