### ISSUE TITLE
QoS 1 PUBLISH must not be resent during the same connection

### ISSUE THREAD

**Issue by HiwayChe** [hivemq/hivemq-mqtt-client#491]
Hi, I am using mqtt-1.2.2.jar as client to sub with broker, my broker is emqx-4.2.2, my iot equipment use mqttV3.1 to pub and my java code use mqttV5 to sub(I don't know if it is ok to use different mqtt version protocol to sub and pub).
Sometimes there will be an error message in log:

` 2021-06-09 19:29:30.806 [com.hivemq.client.mqtt-10-2] ERROR c.h.c.i.m.h.p.incoming.MqttIncomingQosHandler:51 - QoS 1 PUBLISH (MqttStatefulPublish{stateless=MqttPublish{topic=BGT1/1918BD000186/PeriodReportBin, payload=65byte, qos=AT_LEAST_ONCE, retain=false}, packetIdentifier=419, dup=false, topicAlias=0, subscriptionIdentifiers=[9]}) must not be resent (MqttStatefulPublish{stateless=MqttPublish{topic=BGT1/1918BD000186/PeriodReportBin, payload=65byte, qos=AT_LEAST_ONCE, retain=false}, packetIdentifier=419, dup=true, topicAlias=0, subscriptionIdentifiers=[9]}) during the same connection`

I viewed the source code: `com.hivemq.client.internal.mqtt.handler.publish.incoming.MqttIncomingQosHandler#readPublishQos1`

![image](https://user-images.githubusercontent.com/5837440/121643876-e9cf2680-cac4-11eb-90f5-aada0f9c5026.png)

I wonder why `QoS 1 PUBLISH must not be resent during the same connection`? I did not find detailed message in mqtt5 spec(https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901236).

**Comment by LBrandl** [comment]
Hi HiwayChe,
If clients with different MQTT versions are supported depends on the broker implementation. I don't know if this is the case for emqx-4.2.2 but both clients where able to connect, I would assume that it works.
The MQTT 5 spec states under "4.4 Message delivery retry" that:
"When a Client reconnects with Clean Start set to 0 and a session is present, both the Client and Server MUST resend any unacknowledged PUBLISH packets (where QoS > 0) and PUBREL packets using their original Packet Identifiers. This is the only circumstance where a Client or Server is REQUIRED to resend messages. **Clients and Servers MUST NOT resend messages at any other time**"

**Comment by HiwayChe** [comment]
Hi @LBrandl,
`"When a Client reconnects with Clean Start set to 0 and a session is present, both the Client and Server MUST resend any unacknowledged PUBLISH packets (where QoS > 0) and PUBREL packets using their original Packet Identifiers. This is the only circumstance where a Client or Server is REQUIRED to resend messages. Clients and Servers MUST NOT resend messages at any other time"`
does it mean that emqx broker should not resend this message to me? is it a bug for emqx broker?

**Comment by LBrandl** [comment]
The broker should not resend the message to the MQTT v5 client if it doesn't reconnect. Maybe the resend behaviour is configurable. Could be worth checking the broker documentation on that.

**Comment by HiwayChe** [comment]
@LBrandl thanks for yr reply.  I report this question to emqx `https://github.com/emqx/MQTTX/issues/599#issuecomment-859390449`, they say:`If qos 1 message ack timeout, EMQ X resend message by dup message.`, it sounds reasonable, and I did not find details about message retry when ack timeout in mqtt spec doc. 
It seems coming to a dead end, perhaps what can I do is to subscribe using mqttV3。

**Comment by LBrandl** [comment]
Timeouts for ACKs are not intended by the MQTT v5 spec, therefore you will not find any details about retries in this case. Both client and broker are not supposed to resend messages if the connection is stable.

**Comment by SgtSilvio** [comment]
I close this issue here as this is a bug of emqx.
emqx does not adhere to the MQTT 5 specification regarding the statement `Clients and Servers MUST NOT resend messages at any other time` because `If qos 1 message ack timeout, EMQ X resend message by dup message.` violates the specification.
Feel free to comment if something is still unclear.

**Comment by HiwayChe** [comment]
@SgtSilvio , what if consumer ack timeout, does broker will resend same message to guarantee qos 1?

**Comment by manojrawat650** [comment]
> I close this issue here as this is a bug of emqx. emqx does not adhere to the MQTT 5 specification regarding the statement `Clients and Servers MUST NOT resend messages at any other time` because `If qos 1 message ack timeout, EMQ X resend message by dup message.` violates the specification. Feel free to comment if something is still unclear.

@SgtSilvio, the hivemq client 1.2.2 disconnects with error "QOS1 publish must not be resent during the same connection" if a QOS1 message is resent by the broker in case the message was not acknowledged earlier.
Does it mean that for this to work we will have to disconnect and reconnect on the same session? But according to MQTT spec if we gracefully disconnect a client then the session state will be lost and the broker will not resend the QOS1 message.
