### ISSUE TITLE
Server closed connection without DISCONNECT.

### ISSUE THREAD

**Issue by liulongblog** [hivemq/hivemq-mqtt-client#506]
DisconnectedListener log :
2021-09-15 13:53:12.739  INFO 12892 --- [client.mqtt-4-6] com.....mqtt.MqttClient   : [MqttClient] disconnected by SERVER, cause {}

com.hivemq.client.mqtt.exceptions.ConnectionClosedException: Server closed connection without DISCONNECT.

client config as follow:
 Mqtt3ClientBuilder mqtt3ClientBuilder = com.hivemq.client.mqtt.MqttClient.builder()
                .useMqttVersion3()
                .identifier(clientId)
                .serverHost(StringUtils.substringBetween(properties.getUrl(), "//", ":"))
                .serverPort(Integer.parseInt(StringUtils.substringAfterLast(properties.getUrl(), ":")))
                .addConnectedListener(mqttClientConnectedListener)
                .addDisconnectedListener(mqttClientDisconnectedListener)
              
                .automaticReconnect(MqttClientAutoReconnect.builder().initialDelay(5, TimeUnit.SECONDS)
                        .maxDelay(2, TimeUnit.MINUTES).build());
       
        if (properties.getAuthType() == AuthTypeEnum.USERNAME) {
            mqtt3ClientBuilder = mqtt3ClientBuilder.simpleAuth().username(properties.getUsername())
                    .password(properties.getPassword().getBytes(
                            StandardCharsets.UTF_8))
                    .applySimpleAuth();
        } else if (properties.getAuthType() == AuthTypeEnum.X509) {
           
        }
        this.client = mqtt3ClientBuilder.buildAsync();

can i consume that is a problem of server？

**Comment by liulongblog** [comment]
solved

**Comment by dinhthaidaica** [comment]
@liulongblog Could you explain why did it happen and how to fix? 
I ran into the same issue and couldn't figure it out.

**Comment by dinhthaidaica** [comment]
It seems to be a `Mqtt5Client` problem. It just disappeared when I switched to `Mqtt3Client`. 
So my best guess is incompatible between **Client** and **Broker**.

**Comment by liulongblog** [comment]
> It seems to be a `Mqtt5Client` problem. It just disappeared when I switched to `Mqtt3Client`. So my best guess is incompatible between **Client** and **Broker**.

my problem :client connect without synchronized, the same clientid was kicked by server
