### ISSUE TITLE
导致应用崩溃   com.hivemq.client.internal.mqtt.-$$Lambda$8XwOwflQFtWxajl986zuohwMl00

### ISSUE THREAD

**Issue by StevenYan88** [hivemq/hivemq-mqtt-client#517]
java.lang.NoClassDefFoundError: com.hivemq.client.internal.mqtt.-$$Lambda$8XwOwflQFtWxajl986zuohwMl00
        at com.hivemq.client.internal.mqtt.MqttRxClientBuilder.simpleAuth(MqttRxClientBuilder.java:76)
        at com.hivemq.client.internal.mqtt.MqttRxClientBuilder.simpleAuth(MqttRxClientBuilder.java:39)

**Comment by SgtSilvio** [comment]
Hi @StevenYan88 
It seems that you are on Android.
Please follow this guide: https://hivemq.github.io/hivemq-mqtt-client/docs/installation/android/
If that does not work, please provide more information (for example Android build tool versions)

**Comment by pglombardo** [comment]
Hi @StevenYan88 - It seems this issue has gone stale.  If this is still an issue for you, could you file another issue with details on how we can reproduce the issue and environment details?

Thanks for letting us know and please don't hesitate to get in touch if anything remains.
