### ISSUE TITLE
send message block

### ISSUE THREAD

**Issue by HiwayChe** [hivemq/hivemq-mqtt-client#518]
send thread blocks here at line 83:
![image](https://user-images.githubusercontent.com/5837440/147520991-18222fff-2ab4-491f-9622-9f0394154b2c.png)

this is how client creates:
![image](https://user-images.githubusercontent.com/5837440/147521051-e6df000a-7a34-45cd-bdb7-d402ec1f0c55.png)

mtt broker I used is Emqx4.2.2, I did not find error message in emqx error log. 
Is this a hivemq client problem or emqx problem? what should I do to find solutions?

**Comment by HiwayChe** [comment]
hivemq client version is 1.2.2

**Comment by SgtSilvio** [comment]
Hi @HiwayChe 
as you call a blocking operation (`CompletableFuture.get()`), your current thread is blocked until the operation completes.
The publish operation completes if the client receives the acknowledgement packet from the server.

> what should I do to find solutions?
I would suggest looking at which packets are sent/received. For example you could use Wireshark on the same machine where the client is running on and filter for `mqtt`.

**Comment by pglombardo** [comment]
Hi @HiwayChe - since this issue has gone stale could you let us know if it's still an issue for you?  We've had quite a few releases since then.  If it is, could you try it with the latest version of the client?

Thanks - let us know.  We'd be more than happy to pick up the investigation on this.

**Comment by pglombardo** [comment]
Hi @HiwayChe - given the age of this issue I'll close it out.  If it's still an issue for you let us know.  We'd be happy to help out!
