### ISSUE TITLE
[Persistent Sessions] Broker sends message before re-subscribing

### ISSUE THREAD

**Issue by sirtoobii** [hivemq/hivemq-mqtt-client#521]
## Expected behavior

A client starts a session and subscribes to various topics. After some time, the client disconnects (not unexpectedly) and then
reconnects again with `cleanSession=false`, subscribes to the same topics  and receives these messages which were sent during his disconnected phase.

## Actual behavior

After the reconnect, the server acknowledges the session persistence and immediately  sends the messages in his queue - before the client has time to resubscribe. Interestingly, the client acknowledges the messages, however, the `onMessage` callback is not fired. 

- 1. Reconnect and Ack
- 2. Server sends missed message / Client Ack
- 3. Client subscribes to topics / Server Ack

![image](https://user-images.githubusercontent.com/1969330/147860384-4ec39e3a-45ad-4506-8968-c83444f5f576.png)

I also tried other brokers but got the same behavior

### Reproducer code

```kotlin

val client = Mqtt5Client.builder()
        .serverHost(mqttBroker)
        .identifier(uuid)
        .automaticReconnectWithDefaultConfig()
        .buildAsync()

client.connectWith()
            .cleanStart(false)
            .keepAlive(30)
            .sessionExpiryInterval(300)
            .send()
            .whenComplete { ack, throwable ->
                if (throwable != null) {
                    onFailure.invoke()
                } else {
                    //Here we call subscribeWith()
                    onConnected.invoke()
                }
            }
// Ordinary disconnect
client.disconnectWith()
            .sessionExpiryInterval(300)
            .send()

```

## Details
- Affected HiveMQ MQTT Client version(s):  1.2.2
- Used OS (name and version): Android API Level 31

**Comment by MicWalter** [comment]
Hi @sirtoobii,

> After the reconnect, the server acknowledges the session persistence and immediately sends the messages in his queue - before the client has time to resubscribe. Interestingly, the client acknowledges the messages

This is correct behaviour as you don't overwrite the session when you reconnect, so the server still has the clients session stored and therefore knows the clients current subscriptions and the clients queued messages (which he will send out as soon as the connection is established, as you can see from your Wireshark image).

> however, the onMessage callback is not fired.

Can you please provide your code? This seems to be something that doesn't relate to the hivemq-mqtt-client code because there exists no `onMessage()` method.

Greetings,
Michael from the HiveMQ team

**Comment by SgtSilvio** [comment]
In addition to what @MicWalter said:
You can call `subscribe` before `connect`, so that the callback is already registered when the first queued messages arrive.

**Comment by sirtoobii** [comment]
Thank you very much for your help :)

> Can you please provide your code? This seems to be something that doesn't relate to the hivemq-mqtt-client code because there exists no onMessage() method.

Well, I was a bit unspecific here, with `onMessage()` I meant the callback which is fired when a message is published to a subscribed topic...

> You can call subscribe before connect, so that the callback is already registered when the first queued messages arrive.

This is exactly what I was looking for I wasn't aware of this and thought you can only subscribe when there is an active connection

**Comment by SgtSilvio** [comment]
I will close this issue, if you have additional questions, don't hesitate to comment or open a new issue
