### ISSUE TITLE
can not publish when consuming?

### ISSUE THREAD

**Issue by HiwayChe** [hivemq/hivemq-mqtt-client#522]
![F2955B09-8F39-4a5d-B21D-6EBFCFCCB403](https://user-images.githubusercontent.com/5837440/148488407-0fa46a14-4bf0-454a-8fb8-572f94ee4f9c.png)

I use mqtt5 async client to consume message using callback, in callback (not completed yet) I publish a message,  thread blocked, is it normal?

**code snippet:**
consume callback:
![image](https://user-images.githubusercontent.com/5837440/148488747-cb1b3d7f-4a3c-448d-9d27-3b863303fe16.png)

sync send:
![image](https://user-images.githubusercontent.com/5837440/148488883-9b8db934-3618-4c62-b9e6-2da025f895c8.png)

As thread stack shows: thread blocked at `send().get()`.

**Comment by HiwayChe** [comment]
**reproduce code**
`
public class MqttTest {

    interface MqConsumeCallback {
        void onConsume(String topic, byte[] payloadBytes, long delay);
    }

    private static final String topic = "a.b.c";

    private static AtomicLong count = new AtomicLong();

    public static void main(String[] args) throws ExecutionException, InterruptedException {
        MqttTest test = new MqttTest();
        test.connect();

        test.sub(topic, (topic, payloadBytes, delay) -> {
            String message = new String(payloadBytes);
            System.out.println("message received: " + message + ", thread=" + Thread.currentThread().getName());
            test.pub("d.e.f", "send message while consuming".getBytes());
        });

        new Thread(() -> {
            while (true) {
                Uninterruptibles.sleepUninterruptibly(500, TimeUnit.MILLISECONDS);
                test.pub(topic, ("message " + count.incrementAndGet()).getBytes());
            }
        }, "sender-thread").start();
    }

    private MqttConnectConfig mqttConfig = new MqttConnectConfig();

    {
        mqttConfig.setHost("192.168.0.220");
        mqttConfig.setPort(48082);
        mqttConfig.setUsername("fake");
        mqttConfig.setPassword("fake");
    }

    private Mqtt5AsyncClient client;

    private MqttQos DEFAULT_QOS = MqttQos.AT_LEAST_ONCE;

    private int messageExpiry = 120;

    private void connect() throws ExecutionException, InterruptedException {
        client = Mqtt5Client.builder()
                .identifier("mqtt_test").automaticReconnectWithDefaultConfig()
                .serverHost(mqttConfig.getHost()).serverPort(mqttConfig.getPort())
                .addConnectedListener(context -> {
                    System.out.println("connected");
                })
                .addDisconnectedListener(context -> {
                    System.err.println("disconnected");
                })
                .buildAsync();
        MqttConnect mqttConnect = new MqttConnect(30, false, 120,
                MqttConnectRestrictions.DEFAULT, new MqttSimpleAuth(MqttUtf8StringImpl.of(mqttConfig.getUsername()), ByteBuffer.wrap(mqttConfig.getPassword().getBytes())),
                null, null, MqttUserPropertiesImpl.NO_USER_PROPERTIES);

        Mqtt5ConnAck ack = client.connect(mqttConnect).get();
    }

    private boolean pub(String topic, byte[] bytes) {
        if (client == null) {
            throw new IllegalStateException("client is null");
        }
        boolean connected = this.client.getState().isConnected();
        if (!connected) {
            throw new IllegalStateException("client not connected");
        }
        try {
            Mqtt5PublishResult result = this.client.publishWith().topic(topic).qos(DEFAULT_QOS).payload(bytes).messageExpiryInterval(this.messageExpiry)
                    .send().get();
            result.getError().ifPresent(Throwable::printStackTrace);
            System.out.println("pub success, message=" + new String(bytes) + ", thread=" + Thread.currentThread().getName());
            return true;
        } catch (Exception ee) {
            ee.printStackTrace();
            return false;
        }
    }

    public void sub(String topic, MqConsumeCallback mqConsumeCallback) throws ExecutionException, InterruptedException {
        if (client == null) {
            throw new IllegalStateException("client is null");
        }
        this.client.subscribeWith().topicFilter(topic).qos(DEFAULT_QOS).callback((mqtt5Publish) -> {
            mqConsumeCallback.onConsume(topic, mqtt5Publish.getPayloadAsBytes(), -1);
        }).send().get();
        System.out.println("sub success, thread=" + Thread.currentThread().getName());
    }
`

![image](https://user-images.githubusercontent.com/5837440/148499945-64da9b69-5861-4509-b6c7-696b829e1003.png)


after running several seconds, both sub and pub thread are blocked. comment `test.pub("d.e.f", "send message while consuming".getBytes());` in consume callback, it works very well.

**Comment by pglombardo** [comment]
Hi again @HiwayChe - same question here.  Is this still an issue for you?

**Comment by pglombardo** [comment]
I'll close this issue out but if anything remains, let us know.
