### ISSUE TITLE
Example doesn't work with Android 12

### ISSUE THREAD

**Issue by Halabdelkrim** [hivemq/hivemq-mqtt-client#532]
## Expected behavior
Connect to the broker
## Actual behavior
I use the same steps described in this page [https://www.hivemq.com/blog/mqtt-client-library-enyclopedia-paho-android-service/]([https://www.hivemq.com/blog/mqtt-client-library-enyclopedia-paho-android-service/](https://github.com/hivemq/hivemq-mqtt-client/issues/url)), but the application crashes once the connect button clicked.
## Details
- Affected HiveMQ MQTT Client version(s): 
- Used JVM version: 
- Used OS (name and version): Android 12
- Used MQTT version: 
- Used MQTT broker (name and version):

**Comment by oreillymj** [comment]
Can you post the error you see in Android Studio/Logcat

**Comment by pglombardo** [comment]
Hi @Halabdelkrim - do you have any updates on this issue?

Considering the post was written in 2015, it may likely need some updates to follow recent changes.

If I don't hear back, I'll forward the details to the original blog post guest author and close out this issue.

**Comment by Halabdelkrim** [comment]
Hi @pglombardo

Unfortunately, No.

I completely changed the platform from Android Studio to Visual Studio "Xamarin". 

Now, everything works well.

**Comment by pglombardo** [comment]
That's great to hear.  Hopefully you didn't burn too much time with the issue under Android Studio.

I'll close this issue then.  If anything else comes up, feel free to get in touch!
