### ISSUE TITLE
The links in your doc are broken

### ISSUE THREAD

**Issue by david-westerman-dsg** [hivemq/hivemq-mqtt-client#540]
## Expected behavior
When I click on the links in the client configuration page, I expected to see the new documentation page.

## Actual behavior
I am getting a 404 - page not found

### Steps

1. Go to client configuration page:
https://hivemq.github.io/hivemq-mqtt-client/docs/client-configuration/

2. Click on Transports link beside the websockets entry in the Transport Configuration section (but this seems to happen with all the links).
https://hivemq.github.io/hivemq-mqtt-client/docs/client-configuration/transports/websocket.md

3. Get Page not found.

## Details
- Affected HiveMQ MQTT Client version(s): 
- Used JVM version: 
- Used OS (name and version): 
- Used MQTT version: 
- Used MQTT broker (name and version):

**Comment by pglombardo** [comment]
Hey @david-westerman-dsg - thanks for the report and apologies the late reply.  I'll see if we can fix this soon.

**Comment by pglombardo** [comment]
Those pages haven't been written yet hence the dead links.  I've removed the links for now.  Thanks for pointing this out @david-westerman-dsg!
