### ISSUE TITLE
Dependency to `jdk.unsupported`

### ISSUE THREAD

**Issue by sveba** [hivemq/hivemq-mqtt-client#558]
## Expected behavior
No dependency to `jdk.unsupported`

## Actual behavior
ClassNotFound Exception if module `jdk.unsupported` not packaged in the runtime

### Steps
create a JDK without the `jdk.unsupported`  module and run a client with this JDK
 
## Details
- Affected HiveMQ MQTT Client version(s):  1.3.0
- Used JVM version: 17
- Used OS (name and version):  Linux
- Used MQTT version:  5
- Used MQTT broker (name and version): mosquitto 2.15.0

**Comment by pglombardo** [comment]
Hi @sveba - thanks for pointing this out.  Let us have a look and we'll post back soon.

**Comment by pglombardo** [comment]
Late but closing this out per @sveba's comment on https://github.com/traccar/traccar/pull/5009#issuecomment-1430511587

Hope all is well @sveba - if you need anything from us, let us know.  We'd be happy to help!
