### ISSUE TITLE
 Message arrival callback to broker

### ISSUE THREAD

**Issue by marcelofilho** [hivemq/hivemq-mqtt-client#560]
## Checklist

- [X ] I've searched the project's [`issues`](https://github.com/hivemq/hivemq-mqtt-client/issues?q=is%3Aissue).
- [ X] I've searched the project's [`discussions`](https://github.com/hivemq/hivemq-mqtt-client/discussions).

## ❓ Question

How can I know if a published message actually arrived at the broker?

Is it possible to have a callback using `publishWith` or something like that

## 📎 Additional context

I'm having trouble publishing messages to the broker. I use Mqtt3AsyncClient configuring port and url and to publish the message I use publishWith in this way

```
if (client.state.isConnectedOrReconnect){
                client.publishWith()
                    .topic("${Server.TOPIC_HISTORICAL}${data.serialNumber}")
                    .payload(data.data)
                    .qos(MqttQos.AT_LEAST_ONCE)
                    .retain(false)
                    .send()
```

The problem is that my internet fluctuates a lot, and it is very slow. The client does not disconnect and continues to send data. With that I lose a lot of data during my session. Would there be any way for me to know if the package actually arrived at the broker? So it would only send the next message if the current message arrived successfully. I looked in the documentation and found nothing.

note: qos AT_LEAST_ONCE for some reason does not guarantee the arrival of the packet, I think it is because there is not a strong enough connection and the application does not stop sending packets

**Comment by pglombardo** [comment]
Hi @marcelofilho,

QoS `AT_LEAST_ONCE` actually does guarantee the arrival of the package to the broker.  That level requires that the MQTT broker respond with a `PubAck` message.  Only then is the operation complete.

For reference/comparison, there is a good explanation of all the Quality of Service ins and outs [here](https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/).

> QoS level 1 guarantees that a message is delivered at least one time to the receiver. The sender stores the message until it gets a [PUBACK](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718043) packet from the receiver that acknowledges receipt of the message. It is possible for a message to be sent or delivered multiple times.

`publishWith` returns a `CompletableFuture`.  You need to wait on that future to complete to know that the publish got acknowledged by the broker.  e.g. When that future completes, it means that the MQTT broker responded with the `PubAck` acknowledgement.

Here's an example that does nothing.

```java
client.connect()
        .thenCompose(connAck -> client.publishWith()
                    .topic("${Server.TOPIC_HISTORICAL}${data.serialNumber}")
                    .payload(data.data)
                    .qos(MqttQos.AT_LEAST_ONCE)
                    .retain(false)
                    .send())
        .thenCompose(publishResult -> client.disconnect());
```

Let me know if this helps.

**Comment by pglombardo** [comment]
Apologies...  I didn't post the best example.  Take a look at [the example here](https://github.com/hivemq/hivemq-mqtt-client/blob/master/examples/src/main/java/com/hivemq/client/mqtt/examples/AsyncDemo.java#L36-L41).

```java
client.connect()
        .thenAccept(connAck -> System.out.println("connected " + connAck))
        .thenCompose(v -> client.publishWith().topic("demo/topic/b").qos(MqttQos.AT_LEAST_ONCE).send())
        .thenAccept(publishResult -> System.out.println("published " + publishResult))
        .thenCompose(v -> client.disconnect())
        .thenAccept(v -> System.out.println("disconnected"));
```

Try pasting this block into your code.  It should do the job.

or alternatively, to debug you could flip to the blocking client:

```java
MqttPublishResult publishResult = (MqttPublishResult) client.toBlocking().publishWith()
                .topic("demo/topic/a")
                .qos(MqttQos.AT_LEAST_ONCE)
                .payload("payload".getBytes())
                .retain(true)
                .contentType("text/plain")  // our payload is text
                .messageExpiryInterval(120) // not so important, expire message after 2min if can not be delivered
                .send();

System.out.println("published " + publishResult);
```

This blocking client example can be [found here](https://github.com/hivemq/hivemq-mqtt-client/blob/master/examples/src/main/java/com/hivemq/client/mqtt/examples/Mqtt5Features.java#L85-L96).

> I tried in every way to get some feedback that the data was received by the broker, and I can't do that. The internet here is really bad and clearly the data was not received but there are no exceptions, this is very strange.

Are your consumers receiving the data?

> I think I'm not understanding how the CompleteFuture works. thank you very much if you can help me.
thanks again for your answer

Async can be a bit complex.  Futures are scheduled to run on an event loop - the result is only available after execution is complete. 

Hopefully this gets you on the right path.  Let me know.

**Comment by marcelofilho** [comment]
hey @pglombardo apologies for the delay. I don't even know how to thank you, but it worked. Apparently toBlocking() blocks the next message until the broker confirms receipt of the previous message. Really thank you.
