### ISSUE TITLE
Maven central latest version is 1.3.0 althouth 1.3.1 was released last week

### ISSUE THREAD

**Issue by skrutzler** [hivemq/hivemq-mqtt-client#569]
## ❓ Question

It seems that the maven deploy job did not work as expected for the new release (see https://github.com/hivemq/hivemq-mqtt-client/deployments/activity_log?environment=mavenCentralPublish)

maven-central should show 1.3.1 but the latest version available is 1.3.0 (https://search.maven.org/artifact/com.hivemq/hivemq-mqtt-client)

Error during maven deploy job:
 > Task :releaseSonatypeStagingRepository FAILED
FAILURE: Build failed with an exception.
40 actionable tasks: 40 executed

>* What went wrong:
Execution failed for task ':releaseSonatypeStagingRepository'.
>> Staging repository is not in desired state [released, not_found]: StagingRepository(id=comhivemq-1293, state=closed, transitioning=false). It is unexpected. Please checkNexus logs using its web interface - it can be caused by validation rules violation. If not, please report it to https://github.com/gradle-nexus/publish-plugin/issues/ with '--info' logs

**Comment by pglombardo** [comment]
The 1.3.1 release has been fixed: https://repo1.maven.org/maven2/com/hivemq/hivemq-mqtt-client/

The Maven/Sonatype UIs will update in 24 hours.

Thanks for reporting and the patience @skrutzler!
