### ISSUE TITLE
Reconnect not working depending on where credentials are provided

### ISSUE THREAD

**Issue by inad9300** [hivemq/hivemq-mqtt-client#574]
## 🐛 Bug Report

If credentials are provided to `Mqtt5ClientBuilder`, reconnections to a broker when the broker is restarted work. However, when provided to `Mqtt5ConnectBuilder` (as exemplified in the [docs](https://hivemq.github.io/hivemq-mqtt-client/docs/mqtt-operations/connect/#simple-auth-username--password)), initial connections work but reconnections don't! The following error message is displayed:

> CONNECT failed as CONNACK contained an Error Code: BAD_USER_NAME_OR_PASSWORD.

What is the difference between providing them in one place versus the other? I was shocked to find that there were two possible places, to be honest, and it took me a long time to come to this lucky realization, given the lack of documentation.

During the course of my investigation, I sometimes saw a different warning related to SSL (which I'm not using), saying "Username: null; SSL certificate subject DN: unavailable". They appeared with the same frequency as I have configured reconnects to occur, so they must have been logged on reconnection attempts. I'm not sure if these warnings stem from the same problem or not, but they don't show up anymore.

## 🔬 How To Reproduce

1. Start an MQTT client and server
2. Restart the server (I'm using docker, so I use `docker compose restart mqtt_server`)
3. Verify that the client is automatically reconnected to the server in one case but not the other

### Code sample

```
var client = Mqtt5Client
    .builder()
    .serverHost("host")
    .serverPort(port)
    // When using these, both connecting and reconnecting work:
    .simpleAuth()
    .username("user")
    .password("password".getBytes())
    .applySimpleAuth()
    .automaticReconnect()
    .initialDelay(1, SECONDS)
    .maxDelay(1, SECONDS)
    .applyAutomaticReconnect()
    .identifier(randomUUID().toString())
    .buildAsync();

var connAck = client
    .connectWith()
    .sessionExpiryInterval(60)
    // When using these, connection works but reconnection does not:
    // .simpleAuth()
    // .username("user")
    // .password("password".getBytes())
    // .applySimpleAuth()
    .send()
    .get(30, SECONDS);
```

### Environment

Where are you running/using this client? Docker
What version of this client are you using? 1.3.1
JVM version? 17
Operating System? Ubuntu
Which MQTT protocol version is being used? 5
Which MQTT broker (name and version)? Apache ActiveMQ Artemis 2.28.0

**Comment by sauroter** [comment]
Hi @inad9300,

this is intentional behaviour. 

1. If you set the credentials on the client, this instance of the clients will use them for every connection attempt where they are not explicitly overwritten. As the name `MqttClientBuilder` suggests the scope of the builder is for the whole life time of the client.
2. If you set the credentials in the `MqttConnectBuilder` it is only scoped to exactly the one CONNECT package you are building. Basically you are overwriting the automatically generated CONNECT package with your own. Thats why the  method is called `connectWith()`.

I hope this helps.
If you have more questions feel free to ask

All the best

**Comment by inad9300** [comment]
It's rather confusing, but I understand. It'd be good to document this accurately.
