### ISSUE TITLE
Getting "java.net.UnknownHostException: No such host is known (************.s2.eu.hivemq.cloud)" 

### ISSUE THREAD

**Issue by aks2687** [hivemq/hivemq-mqtt-client#576]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/hivemq/hivemq-mqtt-client/issues?q=is%3Aissue).
- [x] I've searched the project's [`discussions`](https://github.com/hivemq/hivemq-mqtt-client/discussions).

## ❓ Question

I am getting "java.net.UnknownHostException: No such host is known (*************.s2.eu.hivemq.cloud)" when running from Intellij from a Java program using the Javaclient. From the browser I am able to establish the connection using the webclient provided by the HiveMQ 
 
I am running the program from a system which is behind a proxy. Configured the proxy server and other links are resolved from Intellij without any issues. 

Any hints to check the issue would be of great help ?

**Comment by pglombardo** [comment]
Hi @aks2687 - this issue seems to have gone stale.  Is this still an issue for you?

**Comment by pglombardo** [comment]
Hi @aks2687 - I'll close this issue out but if this is still an issue for you, let us know.  We'd be happy to help out!
