### ISSUE TITLE
How to force cancel/interrupt a reconnecting state client?

### ISSUE THREAD

**Issue by bigcat26** [hivemq/hivemq-mqtt-client#582]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/hivemq/hivemq-mqtt-client/issues?q=is%3Aissue).
- [x] I've searched the project's [`discussions`](https://github.com/hivemq/hivemq-mqtt-client/discussions).

## ❓ Question

How to force cancel/interrupt a reconnecting state client?

## 📎 Additional context

When I try to disconnect a Mqtt3RxClient that is in the DISCONNECTED_RECONNECT state, it returns a throwable with the message ‘com.hivemq.client.mqtt.exceptions.MqttClientStateException: MQTT client is not connected.’ However, it may still successfully reconnect after a while, which is not what I want. I need to force an interruption of the reconnecting process immediately, such as by closing the underlying socket, but I did not find any API to access the underlying socket. Do you have any suggestions?

**Comment by pglombardo** [comment]
Would this do it or do you have to specifically interrupt a hanging socket?

```java
.addDisconnectedListener(context -> {
    context.getReconnector()
        .reconnect(false);
})
```

More examples in [this file](https://github.com/hivemq/hivemq-mqtt-client/blob/bb5dee551e1e19edbc4d6a9b19037a616a05db4f/examples/src/main/java/com/hivemq/client/mqtt/examples/ReconnectStrategy.java).

**Comment by bigcat26** [comment]
> @bigcat26 How did you fix this? We are experiencing the same issue.

I have applied the following changes in `MqttDisconnectCompletable.java`:

```java
    protected void subscribeActual(final @NotNull CompletableObserver s) {
        final MqttClientConnectionConfig connectionConfig = clientConfig.getRawConnectionConfig();
        if (connectionConfig == null) {
//            EmptyDisposable.error(MqttClientStateExceptions.notConnected(), s);
            clientConfig.getRawState().set(MqttClientState.DISCONNECTED);
            clientConfig.releaseEventLoop();
            EmptyDisposable.complete(s);
            return;
        }
```

It seems works.
