### ISSUE TITLE
How to subscribe with a custom subscription identifier?

### ISSUE THREAD

**Issue by andsel** [hivemq/hivemq-mqtt-client#611]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/hivemq/hivemq-mqtt-client/issues?q=is%3Aissue).
- ~~[] I've searched the project's [`discussions`](https://github.com/hivemq/hivemq-mqtt-client/discussions).~~

## ❓ Question

How can I [...]?
I don't know if it's possible and how set `subscription identifier` during the subscribe

Is it possible to [...]?
Set a custom subscription identifier when sending a SUBSCRIBE message to the broker

## 📎 Additional context

```java
subscriber.subscribeWith()
            .topicFilter("/metric/temperature/#")
// --> how to configure here the subscription identifier?
            .send();
```

**Comment by pglombardo** [comment]
Hi @andsel - there is no API for this - this client has been built to manage subscription identifiers automatically internally when it's supported by the broker.

Not all brokers support subscription identifiers (HiveMQ does) so support has to be checked in the CONNACK connect response.

Managing IDs (and their re-use) can be cumbersome when dealing with a lot of subscriptions.

What's your use case/problem to solve?  Maybe we can find an alternative solution...

**Comment by pglombardo** [comment]
Excellent - let me know if you have any issues.
