### ISSUE TITLE
What is use of acknowledge function in Mqtt5Publish class ?

### ISSUE THREAD

**Issue by Shalaka1197** [hivemq/hivemq-mqtt-client#614]
What is use of acknowledge function in Mqtt5Publish class ?
`
void acknowledge();
`

Please let me know if there is any example for this.

**Comment by pglombardo** [comment]
Hi @Shalaka1197 - that function allows for the manual acknowledgement of received publish messages.  Valid for QoS levels 1 and 2, there are certain scenarios where you may have multiple clients receiving messages and only want to acknowledge the message when the client takes ownership of the message.

From the front page README:

<img width="825" alt="Screenshot 2024-03-05 at 13 11 54" src="https://github.com/hivemq/hivemq-mqtt-client/assets/395132/7f9e29c1-6685-4ad5-a238-2e929265f451">


An code example would be along the lines of the following:

```java
final Mqtt5SubAck subAck = client.subscribeWith()
                .topicFilter("demo/topic/a")
                .callback(publish -> {
                    boolean success = false;

                    // Some logic & conditions

                    if (success) {
                        publish.acknowledge();
                    }
                })
                .send().join();
```

I filed issue #621.  We should add documentation on this.

Does the above information answer your question?

**Comment by pglombardo** [comment]
Documentation on manual acknowledgement [has been added here](https://hivemq.github.io/hivemq-mqtt-client/docs/advanced-usage/) as well now.

I'll close out this issue but if anything remains, let us know!
