### ISSUE TITLE
Exception while decoding PUBLISH: topic alias must not exceed topic alias maximum

### ISSUE THREAD

**Issue by deena-philip** [hivemq/hivemq-mqtt-client#617]
Getting the error when receiving a message.

`Exception while decoding PUBLISH: topic alias must not exceed topic alias maximum
`

**Comment by pglombardo** [comment]
Hi @deena-philip - could you provide a bit more information so we can investigate?

1. Which broker are you using?
2. Example client code on how/where this happened so we can try and reproduce this?

Thanks!

**Comment by pglombardo** [comment]
Hi @deena-philip - since I haven't heard back I'll close out this issue but if you want to revisit it, feel free to comment or file a new issue.  We'd love to help out if it's needed!

**Comment by nishankhadka09** [comment]
**Broker: MQTTNet**

> How:

 
1-> Connect to broker from android device A. Success
2 -> Connect to broker from android device B. Success. but Device A disconnects

> Disconnection Reason for Device A:

**com.hivemq.client.mqtt.mqtt5.exceptions.Mqtt5DisconnectException:Exception while decoding PUBLISH: topic alias must not exceed topic alias maximum**

> Reconnection attempt for Device A:

**com.hivemq.client.mqtt.mqtt5.exceptions.Mqtt5ConnAckException: CONNECT failed as CONNACK contained an Error Code: BAD_USER_NAME_OR_PASSWORD.**
