### ISSUE TITLE
Uses cases for below HiveMQ success codes

### ISSUE THREAD

**Issue by Shalaka1197** [hivemq/hivemq-mqtt-client#625]
Please tell me the valid test scenarios for below HiveMQ success codes. Is there any test cases are available for the same ?

-    SUCCESS ,NO_MATCHING_SUBSCRIBERS ,UNSPECIFIED_ERROR , IMPLEMENTATION_SPECIFIC_ERROR, NOT_AUTHORIZED
, TOPIC_NAME_INVALID, PACKET_IDENTIFIER_IN_USE, QUOTA_EXCEEDED , PAYLOAD_FORMAT_INVALID

**Comment by pglombardo** [comment]
Everything we have for this client is open source in this repo.  For example: https://github.com/search?q=repo%3Ahivemq%2Fhivemq-mqtt-client%20NO_MATCHING_SUBSCRIBERS&type=code

**Comment by pglombardo** [comment]
Hi @Shalaka1197 - I'll close this issue out.  If anything remains, feel free to open a new issue!
