### ISSUE TITLE
Can not connect to HiveMQ WebSocket Client

### ISSUE THREAD

**Issue by jumpingliu** [hivemq/hivemq-mqtt-client#634]
## 🔬 How To Reproduce

1. I set up an application and add the broker address as `tcp://broker.mqttdashboard.com:1883`  and returns error as the connnection fails

### Environment

Where are you running/using this client?

What version of this client are you using?

JVM version?

Operating System?

Which MQTT protocol version is being used? 

Which MQTT broker (name and version)?

**Comment by pglombardo** [comment]
Hi @jumpingliu - could you post the error and stack trace?

If you are connecting via websockets, the port you specified is incorrect:

<img width="907" alt="Screenshot 2024-06-27 at 14 48 10" src="https://github.com/hivemq/hivemq-mqtt-client/assets/395132/a9e27765-fb4e-40eb-8546-9f79fc8b5b18">

**Comment by pglombardo** [comment]
Hi @jumpingliu - since I haven't heard back I'll close out this issue but if anything remains, please let us know!
