### ISSUE TITLE
Reconnect Handling (automatic + strategy)

### ISSUE THREAD

**Issue by SgtSilvio** [hivemq/hivemq-mqtt-client#83]
includes:
- [x] Listener which is notified when the client is/was disconnected
- [x] Possibility to inspect the reason for the disconnect (e.g. Disconnect message, closed, error) 
- [x] Possibility to reconnect in this listener with a delay and/or after a future succeeds (for e.g. querying a new OAuth token) 
- [x] Possibility to alter the Connect message 
- [x] Possibility to alter the server address (for e.g. high availability, redirect) 
- [x] Provide default automatic reconnect with exponential backoff strategy 
- [x] Setting of username/password for a client, not only on connect (reuse during reconnect)
- [x] Resending of messages after reconnect (pending + queued, Publishes, Subscribes, Unsubscribes)

**Comment by tejas-n** [comment]
Is it possible to know when this feature is going to be released?

**Comment by SgtSilvio** [comment]
This feature is currently in active development.
We are targeting a release by the end of next week.
You can track the progress via the GitHub project board here: https://github.com/hivemq/hivemq-mqtt-client/projects/2#card-21152062
